### ISSUE TITLE
[Map] Refactor Icons - Use icons within context of the map style instead of HTML elements

### ISSUE THREAD

**Issue by kalimar** [Terrastories/terrastories#100]
By refactoring these icons to be part of the canvas we can take advantage of more Mapbox GL-JS features such as clustering, filtering, and data-driven styling.

Steps
* Organize icons within context of Mapbox style file structure - they will become sprites. This may require first uploading the icons to the mapbox style and downloading again. 
* Add Icons as a layer to map instead of as separate HTML elements

**Comment by mirandawang** [comment]
https://www.mapbox.com/help/define-sprite/

**Comment by kalimar** [comment]
https://blog.mapbox.com/on-wednesdays-we-make-pink-maps-ff147e6615c8 - good intro to the topic of creating custom icons. Doing this will include changing some of the syntax in the Mapbox layer spec of the map.

**Comment by mirandawang** [comment]
closing for now; moving to google doc
