### ISSUE TITLE
[Deployment] Remove the need for port 3000 when loading the app

### ISSUE THREAD

**Issue by kalimar** [Terrastories/terrastories#124]
Our goal is for users to access the offline computers SSID and from their browser just navigate to `Terrastories` (or possibly `terrastories.io`.

**Comment by kalimar** [comment]
I assigned @Bootjack and @robbkidd but mainly cause I need help. Perhaps one or two of us could pair later tonight, Sept. 30th.

**Comment by mirandawang** [comment]
closing for now; moving details to issue google doc
