### ISSUE TITLE
[CMS / i18n] Provide i18n for field names in marker popup, and Administrate content

### ISSUE THREAD

**Issue by rudokemper** [Terrastories/terrastories#150]
We have i18n handling intro page, sidebar, and some Administrate content.

However, there are a few more things that we need to cover using i18n:

* The field names in the marker popup (`Region`, `Type of Place`)
* The names of the models in the Administrate sidebar (`Users`, `Speakers`, `Stories`, `Places`)
* The names of the fields for each model in Administrate (for example, for `Speakers` -- `Photo`, `Name`, `Birthplace`, `Birthdate`)

**Comment by lsfernandes92** [comment]
Hi everyone! Could I take a look on that one?

**Comment by rudokemper** [comment]
Hi @lsfernandes92! Welcome :) please feel free to do so! If you have any questions or would like to join the community, we are in the Terrastories channel on the Ruby for Good Slack group. https://rubyforgood.herokuapp.com/
