### ISSUE TITLE
[Video] Set thumbnail images for video players

### ISSUE THREAD

**Issue by mirandawang** [Terrastories/terrastories#159]
Currently the video player uses a black screen as a thumbnail. Let's see if we can use a screen grab from the video as the thumbnail instead.

**Comment by rudokemper** [comment]
@bkjohnson added a summary of where things were left off at Ruby by the Bay, here: https://github.com/rubyforgood/terrastories/issues/3

**Comment by mirandawang** [comment]
closing for now; moving to google doc
