### ISSUE TITLE
[CMS] Update the Place model and importer (and merge in Point model)

### ISSUE THREAD

**Issue by mirandawang** [Terrastories/terrastories#162]
Update the Point and Place models so they are combined in one model named Place. Let Place have these fields:

name : String (same as the Point model)
type : String
description : String (same as the Point model)
region : String
lat : float (same as the Point model)
long : float (same as the Point model)
photo : String (the img src)

for region and type fields, display in the admin UI when creating a new Place a dropdown of existing values and an input field which can create new values, with some validations to avoid duplicates from casing/spelling/etc. Allow the existing values to be renamed, as well.

**Comment by bperlik** [comment]
I'll work on this one, too. Along with #163 and #164. These are my first open source contributions but I have a mentor that is a principal engineer with Pivotal, very experienced in Ruby on Rails, to guide me. I appreciate any and all comments, suggestions, and criticism for my contribution.

**Comment by rudokemper** [comment]
Thank you so much @bperlik :) Absolutely feel free to reach out if anything comes up. We have a channel #terrastories on the Ruby for Good Slack https://rubyforgood.herokuapp.com/ where everybody who's worked on this app has joined, and can provide any help or insight wherever needed.

**Comment by mirandawang** [comment]
Thank you @bperlik!! We would love your contributions :) We have a CONTRIBUTING.md doc with more instructions for our process, so I hope that is helpful. Otherwise, as Rudo said, please definitely reach out with any questions or comments!

**Comment by alindeman** [comment]
Is this still an issue that needs to be done and with high priority?

@bperlik Did you make headway on this one?

**Comment by bperlik** [comment]
I was under the impression that all issues were completed at Ruby by the Bay? Is that not true?

**Comment by mirandawang** [comment]
@alindeman I believe this one was completed at Ruby by the Bay. Thanks!! 

@bperlik Only a few of the open issues were completed :) I will close the ones that have. The rest are free game! We would love your work on this issue still! https://github.com/Terrastories/terrastories/issues/163
