### ISSUE TITLE
[CMS] Update the Speaker model and importer

### ISSUE THREAD

**Issue by mirandawang** [Terrastories/terrastories#163]
Let's update the Speaker model to match these fields, and allow the csv importer to be able to import these fields. 

name : String
birth_year : String (or DateTime)
birthplace : Place (One to Many relationship)
photo : String (the img src)

When birth_year in 'unknown' for the importer, use 'nil'.

**Comment by bperlik** [comment]
I'll work on this one, too, so similar to #164.

**Comment by bperlik** [comment]
Miranda - This is my very first o/s contribution. I would greatly appreciate any corrections or recommendations on my code, the comments, improvements, etc. TIA. I'm a bit shy about creating a pull request at this point. https://github.com/bperlik/terrastories/tree/163-update-speaker-model
