### ISSUE TITLE
[CMS] Update the Story model and importer

### ISSUE THREAD

**Issue by mirandawang** [Terrastories/terrastories#164]
Let's update the Story model to match these fields and the importer to be able to import these fields through the csv.

title : String
desc : String
where_interviewed : Place (One to Many relationship)
date_interviewed : DateTime
interviewer : String
language : String
video : ActiveStorage Media attachment (Many to Many relationship) 
permission_level : Enum

In the admin UI for interviewer and language, display a drop down of the values that already exist/have been created and an input field where a new value can be created. Add some validations on that field so we can avoid duplicates from casing/spelling/etc.

**Comment by rudokemper** [comment]
There should also be speaker_name and place_name as string tag fields, which can take multiple entries. The importer should be able to parse these entries by using of a comma.

**Comment by bperlik** [comment]
I'll start working on this now. This is my first open source contribution, but I'm very familiar with sql, csv imports, databases, and love Ruby.
