### ISSUE TITLE
[UI] Design a new mobile interface so story list and map can be viewed at the same time

### ISSUE THREAD

**Issue by mirandawang** [Terrastories/terrastories#165]
Currently if you select a story, the map will pan and zoom to that point. However on mobile, the story list covers the map so the user doesn't see the point unless they close the list. We would like to come up with a new interface so the list and map can be viewed at the same time.

**Comment by rudokemper** [comment]
The way ESRI's Shortlist Story Map template handles this could be one approach for this: https://storymaps.arcgis.com/en/gallery/#s=0&md=storymaps-apps:shortlist

**Comment by rudokemper** [comment]
<img width="819" alt="Screen Shot 2018-12-01 at 11 24 20 AM" src="https://user-images.githubusercontent.com/31662219/54574318-4581d680-49c6-11e9-9061-456ca3de0683.png">
<img width="795" alt="Screen Shot 2018-12-01 at 11 24 26 AM" src="https://user-images.githubusercontent.com/31662219/54574319-4581d680-49c6-11e9-935a-add87c6f4d9a.png">

Some wireframes courtesy of the amazing Jazz.

**Comment by rudokemper** [comment]
There are now some amazing wireframes designed by Brandon Cohn: more information forthcoming.

**Comment by mirandawang** [comment]
closing for now; moving to google doc
