### ISSUE TITLE
[Discussion] Separate github instances for Terrastories: Matawai Konde and Terrastories as a SaaS

### ISSUE THREAD

**Issue by rudokemper** [Terrastories/terrastories#170]
At some point, we should place the content specific to Matawai into a separate repository (and protect the community data associated with that project), and make this the more generic SaaS repository.

**Comment by rudokemper** [comment]
Working on a branch with generic front-end design, i18n, dummy map and seed data (focused on the history of Terrastories development at Ruby for Good!):
https://github.com/rubyforgood/terrastories/tree/170-terrastories-generic-content

**Comment by rudokemper** [comment]
I created a PR (https://github.com/Terrastories/terrastories/pull/231) with the following changes:

-Removing references to Matawai in the HTML/CSS;
-Adding Portuguese as a third language option, to demonstrate the i18n functionality;
-Adding a generic world map in the shapefiles and style.json;
-Adding generic seed data, focused on the two Ruby for Good events so far.

(Note that for the seed data, there is one story that is set to restricted.)

Before merging this PR, we should figure out a workflow for creating community branches. I imagine that we could have the following;

`terrastories/` (master, public, generic SaaS content taken from the above PR)
`terrastories-matawai/` (private branch pulling from master with Matawai-specific content)
`terrastories-ulupuene/` (private branch pulling from master with Ulupuene-specific content)
etc.

Thoughts?

**Comment by mirandawang** [comment]
Looks good!! I love that it's mapping the different Ruby for Good events 😊💙

One thing I'm not sure about for the branches is that I don't think specific branches can be private only if it's a public repository. Unfortunately I don't think forks can be private either :/ 

I found this link here (https://steinbaugh.com/posts/git-private-fork.html) which says you can clone a repo into a private one. That seems like it'll work well for having a separate private repo for the different communities w/ their content. But I'm not sure how easy it will be to get updates from the "main" branch.

**Comment by rudokemper** [comment]
Hmm, I see... well, for now it shouldn't be too bad to keep the community-specific files somewhere, and to overwrite those into whatever latest version of Terrastories master whenever setting up a new instance.

Is this one good to merge otherwise? Would love to see it get updated in the Herokuapp build so we can start to show off a demo of Terrastories :)

**Comment by mirandawang** [comment]
Looks good to merge to me! :)
