### ISSUE TITLE
[Server-side] Analytics log for number of times markers, stories are clicked; videos played

### ISSUE THREAD

**Issue by rudokemper** [Terrastories/terrastories#171]
It will be good to have a log file somewhere which counts the number of clicks on markers and stories, and video plays.

**Comment by rudokemper** [comment]
-Amount of time spent having Terrastories open per session
-Video plays (and possibly the amount of time watched per video)
-Story card clicks
-Marker clicks

**Comment by mirandawang** [comment]
closing for now; moving details to issue google doc
