### ISSUE TITLE
[Map] Documenting use of MBtiles / Mapbox Studio / OpenStreetMap for basemap

### ISSUE THREAD

**Issue by rudokemper** [Terrastories/terrastories#175]
In some cases, we need to use offline tiles for the basemap loaded using TileServer. This process is well documented and in fact, the whole architecture of the initial build of Terrastories is constructed around exactly this use scenario.

For online-only deployments of Terrastories, it is much better to use content directly from Mapbox Studio. This was handled for Matawai via [a previous map switcher PR](https://github.com/rubyforgood/terrastories/pull/133/files).

Now, for Terrastories as a SaaS, we should work to document how to easily implement any base map of choice, whether it be (1) locally hosted tiles built with TileBuilder and served via TileServer, (2) Mapbox Studio content, or (3) something like OpenStreetMap or other publicly available maps for users that don't actually need to do any map customization for their instances of Terrastories.

**Comment by mirandawang** [comment]
closing for now; moving details to issue google doc
