### ISSUE TITLE
[UI] Update font color from black to #474747

### ISSUE THREAD

**Issue by mirandawang** [Terrastories/terrastories#183]
Across our app we use black as the default font color for paragraph text. Jazz recommends we use #474747 instead. Update all the spots we use black as the font color to instead use #474747.

**Comment by ElleeB** [comment]
Issues with mysql2 breaking bundle install and update :( Help? @mirandawang

**Comment by mirandawang** [comment]
Hey @ElleeB! Sorry to hear you're having issues. 

Can you paste the error that you're getting?

You can also feel free to join us in the Ruby for Good Slack! We can help you in the #terrastories channel :) https://t.co/kUtI3lnpW1

**Comment by mirandawang** [comment]
@ElleeB I think I know the issue with mysql2 as I just ran into it myself :) You should be running `script/setup` in the root directory if it's your first time install or `script/update` if you are trying to update gems. This will run the commands inside of the docker rails container, rather than in your local. Then, if you run `script/server`, you should see the application start.

**Comment by leosoaivan** [comment]
Might this still be open?

**Comment by rudokemper** [comment]
@leosoaivan sure is :)

**Comment by leosoaivan** [comment]
Alright, I'll take it @rudokemper! Is this something we still want?

**Comment by rudokemper** [comment]
I think so right @mirandawang?

**Comment by ainlovescode** [comment]
Can I help out too? 😃

**Comment by mirandawang** [comment]
@ainlovescode thanks for your interest!! <3 i think @leosoaivan may be working on this already. but please feel free to find a different issue that you would like to work on!

**Comment by leosoaivan** [comment]
@mirandawang yep, working on this one.

Question, I see a few places where we have default black text that isn't specifically set to "black" (like some H3 elements). Do we want to include these elements in the re-styling, as well?
