### ISSUE TITLE
[Map] Tippecanoe convert.sh script needs extra parameters to generate large mbtiles

### ISSUE THREAD

**Issue by rudokemper** [Terrastories/terrastories#195]
For very large shapefiles, the tippecanoe tilebuilder will only generate tiles up to a certain zoom level due to a default limitation. As specified here https://github.com/mapbox/tippecanoe, those tile size limits can be disabled:

> -pf or --no-feature-limit: Don't limit tiles to 200,000 features
-pk or --no-tile-size-limit: Don't limit tiles to 500K bytes

Goal for this ticket: Disable size limits in the convert.sh script to allow for larger tiles

**Comment by mirandawang** [comment]
closing for now; moving details to issue google doc
