### ISSUE TITLE
[Video] Add ability to embed YouTube, Vimeo and videos hosted elsewhere

### ISSUE THREAD

**Issue by rudokemper** [Terrastories/terrastories#202]
It is possible to upload videos directly to Terrastories, but for any online instances of the application, it would be nice to be able to just embed videos already on YouTube or Vimeo to the Stories.

**Comment by rudokemper** [comment]
In addition, it would be nice to be able to point to the URL of a video file to embed. That could be useful for instances that have the media content stored elsewhere (like a Heroku hosted instance of a github repo)

**Comment by j-meyer** [comment]
I could pick this up if no-one else is working on it.

**Comment by rudokemper** [comment]
Please feel free, @j-meyer! :)

**Comment by mirandawang** [comment]
Hey @j-meyer ! Are you still working on this? :)

**Comment by j-meyer** [comment]
Hey, sorry, I've been pretty busy, I can start working on it again, but if someone else wants to pick it up, I'm fine with that.
