### ISSUE TITLE
[Map] adjust Tippecanoe settings to optimally render spatial data

### ISSUE THREAD

**Issue by rudokemper** [Terrastories/terrastories#206]
In the current tilebuilder/tileserver setup, Terrastories seems to have an issue in rendering data points and labels: only a very small selection shows up on the map.

For example, [This branch being developed for Terrastories as a SaaS](https://github.com/rubyforgood/terrastories/tree/170-terrastories-generic-content) has generic world countries and cities point content. This is what it looks like styled in Mapbox Studio:

![capture1](https://user-images.githubusercontent.com/31662219/55292085-3c681080-539b-11e9-863a-49ebab4b2cc2.PNG)

With our setup, it looks like this. Note that there is exclusively one point and label showing up: Inuvik in the far north of Canada.

![capture2](https://user-images.githubusercontent.com/31662219/55292092-4722a580-539b-11e9-9774-72275327b971.PNG)

As you start to zoom, some more labels do show up, but the selection continues to be incomplete. In this screenshot, Cleveland and Columbus should be visible as well:

![capture3](https://user-images.githubusercontent.com/31662219/55292107-7507ea00-539b-11e9-92dc-7f235e9ec05a.PNG)

We should see if it's possible finetune Terrastories so that it can properly render shapefiles akin to Mapbox Studio.

**Comment by rudokemper** [comment]
Update: this may be related to Tippecanoe zoom limits instead of Tileserver:

https://docs.mapbox.com/help/troubleshooting/adjust-tileset-zoom-extent/
https://stackoverflow.com/questions/42772343/tippecanoe-dont-drop-any-points
https://github.com/mapbox/tippecanoe

**Comment by rudokemper** [comment]
By adjusting the tippecanoe configuration, I was able to generate the points as desired for the above map:

![image](https://user-images.githubusercontent.com/31662219/55998075-beedab80-5c8a-11e9-9fa1-c68ab2a63edc.png)

This was done by adding `-zg` and `-Bg` as parameters to the line of script in `convert.sh`. It reads:

`tippecanoe --read-parallel -zg -Bg -o /data/mbtiles/basic.mbtiles $(find /tmp/line -type f | grep .json$)`

This is what these parameters are.

`-zg or --maximum-zoom=g: Guess what is probably a reasonable maxzoom based on the spacing of features.`
`-B zoom or --base-zoom=zoom: Base zoom, the level at and above which all points are included in the tiles (default maxzoom). If you use -Bg, it will guess a zoom level that will keep at most 50,000 features in the densest tile. You can also specify a marker-width with -Bgwidth to allow fewer features in the densest tile to compensate for the larger marker, or -Bfnumber to allow at most number features in the densest tile.`

However, for the Matawai instance, this seems to cut off data; the following lines are shown when running the tilebuilder script:

`Choosing a maxzoom of -z8 for features about 1030 feet (314 meters) apart`
`Choosing a maxzoom of -z11 for resolution of about 129 feet (39 meters) within features`
`Choosing a base zoom of -B0 to keep 20071 features in tile 0/0/0.`
`tile 7/44/62 size is 617925 with detail 12, >500000`
`tile 8/88/124 size is 743667 with detail 12, >500000`

And we can confirm that some of the data is not showing up in certain tile areas.

![image](https://user-images.githubusercontent.com/31662219/55998131-f9574880-5c8a-11e9-80e0-b51e4d8f6f60.png)

So, while the problem has been properly diagnosed, we need to figure out an optimal tippecanoe setting that will work for most of our use cases.

**Comment by mirandawang** [comment]
closing for now; moving details to issue google doc
