### ISSUE TITLE
[CMS] Update all Point references to Place and drop the Point model

### ISSUE THREAD

**Issue by mirandawang** [Terrastories/terrastories#222]
Since we have merged the fields of Point and Place onto the Place model, we should deprecate the use of Point throughout the code. Everywhere that Point is referenced should be updated to the Place model instead.

Once all references to Point are removed, then drop the Point model. 

When this issue is complete, we will have one model, Place, to refer to locations on the map which have Stories and Speakers.

**Comment by rudokemper** [comment]
Note: the seed data in `seeds.rb` would need to be updated as well. Not sure if this warrants a separate issue or not;

**Comment by mirandawang** [comment]
Assigned to @mkmckenzie !
