### ISSUE TITLE
[UI] Add spinners to import buttons

### ISSUE THREAD

**Issue by rudokemper** [Terrastories/terrastories#223]
Currently the import buttons on any of the admin interfaces do not show that they're working. Change the UI to where the button:

1. Is Disabled (we don't want them clicking multiple times)
2. Is Yellow (to indicate something changed)
3. Has a spinner icon (to indicate "progress")

Once the loading is done, restore the button to its previous state.

**Comment by jtu0** [comment]
### Repro steps
1. Login with username and password from `seeds.rb`
1. Click on `ADMIN` button
1. _Import buttons_ are under _Speakers_, _Stories_, and _Places_
