### ISSUE TITLE
[Import/export] Ensure that duplicate items cannot be added to the database

### ISSUE THREAD

**Issue by rudokemper** [Terrastories/terrastories#224]
Currently when the `Stories` and `Places` CSV file are imported, if it's run again it will add duplicate records.

Let's add validations to the `Stories` and `Places` models to ensure that duplicates cannot be created, and that the CSV importer can do idempotent imports. 

Validations are already in place for the `Speakers` importer, the logic for which can be used to update the `Places` and `Stories` importers as well.

**Comment by rgenchev** [comment]
Can I help with adding validations, indexes and tests? I could do that in a new PR.

**Comment by mirandawang** [comment]
Some work has started here, but can be picked up by whoever is available! https://github.com/Terrastories/terrastories/pull/274
