### ISSUE TITLE
[Map] Zoom to maximum extent of filtered points

### ISSUE THREAD

**Issue by rudokemper** [Terrastories/terrastories#226]
In addition to only showing the points that match the stories shown in the sidebar, the map also should zoom to the maximum geographical extent of the points shown on the map, when selecting a filter.

Some discussion about this issue took place at Ruby by the Bay 2019, here: https://github.com/rubyforgood/terrastories/issues/37

**Comment by sansumbrella** [comment]
@kalimar I volunteer!

**Comment by kalimar** [comment]
![](https://media.tumblr.com/tumblr_m0sak5ynil1qlaeuf.gif)
