### ISSUE TITLE
[Docker] Docker containers on dockerhub

### ISSUE THREAD

**Issue by kalimar** [Terrastories/terrastories#232]
Are there any objections to putting our containers on dockerhub? This would potentially save people time when they want to get started with Terrastories since they would pull the container with everything compiled. If y'all agree we can give it a try and then make sure to add that to the docs for how to update Terrastories.

**Comment by amorphid** [comment]
@kalimar 'Twas nice meeting y'all last night :)  

Regarding containers, as you saw last night, I basically spent the majority of the hack night resources, mainly time & battery life, on just setting up Terrastories.  I'm happy to see that you've already taken an interest in exploring the use of publishing the containers.  The only way to see if it's a good idea is to try it.  I have a reasonable amount of experience with Docker, including building & publishing containers, which makes this an easy way for me to get started with Terrastories.  I also love infrastructure & automation in general.

While this topic is being discussed, here's what I'm planning to do:
- build the containers set up on MyLaptop, record how long the build takes, and record the results
- publish the containers I built to my MyDockerHubAccount for testing purposes
- tweak the Terrastories scripts as needed to look for published containers before jumping straight to building them locally
- purge the built containers from my laptop, pull the published test containers, record how long that takes, and record the results

I'll be doing that on Saturday, May 4.

**Comment by kalimar** [comment]
Amazing! Yes please!

**Comment by amorphid** [comment]
FYI, Docker Hub was in read-only mode this past Saturday. so I couldn't test publishing. Will do best to complete this coming weekend :)

**Comment by mirandawang** [comment]
Hey @amorphid! Just wondering if you're still able to work on this :)
