### ISSUE TITLE
[Server-side] Improve docker workflow for devs and prod

### ISSUE THREAD

**Issue by sudo-bmitch** [Terrastories/terrastories#252]
There are a few challenges seen with the docker environment:

- Long build time because of the copies of node_modules
- Slow startup time, especially in prod environments
- Update process can be unpredictable with containers

I'll drop a PR for review to fix these. It will need testing to be sure it doesn't cause issues with the developer workflow since I'm not working with any rails or node changes myself.

**Comment by mirandawang** [comment]
closing for now; moving details to issue google doc
