### ISSUE TITLE
[Video] remove three dots / disable the current behavior which is buggy

### ISSUE THREAD

**Issue by rudokemper** [Terrastories/terrastories#258]
The videos have a button with three dots that shows up at the bottom right.

Currently, when you click that button, the sidebar resets to the top (and the video stops playing).

We should either remove the button (seems possible: https://stackoverflow.com/questions/54507905/html5-video-player-controls-in-chrome-three-dots-on-the-right-open-blank-scree), or make it so that clicking the button does not do anything.

**Comment by khadishi** [comment]
disablepictureinpicture
        controlslist="nodownload noplaybackrate"
