### ISSUE TITLE
[CMS] Add 'community' string field to Speaker model

### ISSUE THREAD

**Issue by rudokemper** [Terrastories/terrastories#262]
The Speaker model should have an additional string field: 'Community'.

Let's add a migration adding this field, and add it to the Speaker UI in Administrate and the Importer module as well.

**Comment by MxOliver** [comment]
I'd be happy to work on this if it's still open

**Comment by rudokemper** [comment]
Please do!

**Comment by MxOliver** [comment]
Added the field to the speaker model and migrated, but I am not totally sure which speaker UI you are referring to. Is it in the stories column when you enter the site, where you can filter by speakers or region? And the importer is that the csv importer?

**Comment by mirandawang** [comment]
@MxOliver It should be the Speaker dashboard when you visit the /admin page, you can click on Speakers in the left rail!

You can find those view files under dashboard https://github.com/Terrastories/terrastories/tree/master/rails/app/dashboards

**Comment by namel3ss** [comment]
Hey, what is the status of this issue? Is it still being worked on?

**Comment by mirandawang** [comment]
@namel3ss Hey there thank you for your interest! There is a current open PR for this issue :)
