### ISSUE TITLE
[UI] Add a visual cue to distinguish between anonymous and restricted content

### ISSUE THREAD

**Issue by mirandawang** [Terrastories/terrastories#266]
If you are logged in as a user, you are able to see more content than someone anonymous.

Let's add some kind of visual marker to distinguish between anonymous and restricted stories and points.

@rudokemper Do you have any ideas as to what this visual marker could be?

Whoever takes on this ticket can feel free to input their design opinion as well! :)

**Comment by rudokemper** [comment]
Perhaps a lock in an unlocked position? That's something most communities everywhere have familiarity with :)
