### ISSUE TITLE
[Map] Adding Sort functionality to the Sidebar

### ISSUE THREAD

**Issue by mirandawang** [Terrastories/terrastories#267]
Currently, all the stories in the Sidebar are displayed in order of most recently added.
We would love to add an option that allows you to sort the list.

Let's start with just being able to sort alphabetical / reverse alphabetical for now.

Then add more sort options in the future!

**Comment by namel3ss** [comment]
Hello, I would like to start working on that! 🙂

**Comment by mirandawang** [comment]
@namel3ss Thank you!!! We would love for you to help with this!

**Comment by namel3ss** [comment]
On it! ;)

**Comment by rudokemper** [comment]
Thanks so much, @namel3ss! :) If you have any questions or would like to join, we also have an active and friendly community on Slack. We're on the #terrastories channel on the Ruby for Good Slack group - https://rubyforgood.herokuapp.com/.

**Comment by namel3ss** [comment]
@rudokemper I am already there! Will post any questions here or there. :)
