### ISSUE TITLE
[Tests] Let's get to 100% Test Coverage!

### ISSUE THREAD

**Issue by kalimar** [Terrastories/terrastories#276]
Terrastories is a very scrappy, amazing application that is starting to grow-up.  With that in mind it's time to start providing test coverage. We could use help with the following:
- [x] Make sure [`rspec`](https://relishapp.com/rspec/docs/gettingstarted) is setup properly.
- [x] Setup the  [`simplecov gem`](https://github.com/colszowka/simplecov).
- [ ] Add a new issue for each test listed in the `simplecov` coverage 

This milestone will be considered reached when the above checklist is completed.

---
**Reference notes**
I've installed the [simplecov](https://github.com/colszowka/simplecov) gem on my computer but even code that reports as having 100% coverage doesn't have passing specs.
I've installed `simplecov` using [these instructions](https://github.com/colszowka/simplecov#getting-started), and here is how I am executing it's commands:

**Running the test suite on the docker container**

`$ docker-compose run web scripts/wait-for-it.sh db:5432 -- "rspec spec"`

**Viewing coverage**

`$ docker-compose up`
`$ docker exec terrastories_web_1 /bin/bash`
`$ open coverage/index.html`

**Comment by sleekybadger** [comment]
@kalimar Hi. I opened https://github.com/Terrastories/terrastories/pull/309 which improves simplecov configuration a little bit. What do you thinking about free CI integrations (for example [travis-ci](https://travis-ci.org), [codecov](https://travis-ci.org/), etc)?

**Comment by kalimar** [comment]
Yeah we definitely want to have something like Travis. Do you want to scope out a ticket? I'm going to add Javascript specs too
