### ISSUE TITLE
[Map] Add style.json validation to tilebuilder

### ISSUE THREAD

**Issue by Bootjack** [Terrastories/terrastories#28]
When generating mbtiles from shapefiles, any discrepancy between the shapefile names in `tilebuilder/shapefiles` and the `source-layer` attributes for the layers in `style.json` will cause a runtime error in the browser when attempting to render the map.

We can guard against this by validating each layer's `source-layer` while iterating through the shape files in `tilebuilder/scripts/convert.sh`. Since most styles will be generated by the online tool provided by MapBox, we're normally only concerned with stripping 6-character alphanumeric hash suffixes matching `/-\w{6}/`.

**Comment by mirandawang** [comment]
closing for now; moving details to issue google doc
