### ISSUE TITLE
[Test] Add test for home_controller

### ISSUE THREAD

**Issue by MxOliver** [Terrastories/terrastories#281]
Add tests for the home_controller (`app/controllers/home_controller.rb`)

**Comment by rgenchev** [comment]
Can I work on this? :)

**Comment by midhunkrishna** [comment]
@rgenchev Are you working on this?

**Comment by rgenchev** [comment]
Yup :)

**Comment by rgenchev** [comment]
I created https://github.com/Terrastories/terrastories/pull/332 with an initial `HomeControllerSpec` file and `describe` blocks for the corresponding controller actions. Since there isn't any logic in the controller, I'm not sure if we want to merge this with empty test file.

**Comment by mirandawang** [comment]
Hey @rgenchev sorry for the confusion! This issue has already been completed here. https://github.com/Terrastories/terrastories/pull/294
Thank you still for the contribution!
