### ISSUE TITLE
[Test] Add test for places_controller

### ISSUE THREAD

**Issue by MxOliver** [Terrastories/terrastories#282]
Add tests for the places_controller (`app/controllers/places_controller.rb`)

**Comment by rgenchev** [comment]
Can I work on this? :)

**Comment by midhunkrishna** [comment]
@rgenchev Are you working on this?

**Comment by rgenchev** [comment]
Yup :)

**Comment by kalimar** [comment]
@midhunkrishna are you comfortable with Javascript tests? I'm getting ready to drop a bunch of issues for those.

**Comment by midhunkrishna** [comment]
@kalimar I am (Apologies for the late reply. I was on vacation until yesterday)

**Comment by rgenchev** [comment]
@midhunkrishna @kalimar, I have a question. I configured `FactoryBot` and added tests for `StoriesController` in https://github.com/Terrastories/terrastories/pull/333. The PR is not merged yet but I'll need the `FactoryBot` configuration and fixtures in this branch. What advice can you give me in this situation? What would be the cleanest solution? Thanks in advance! :)

**Comment by MxOliver** [comment]
@rgenchev I will take a look at that PR and see if we can get it merged tonight, that was you won't have to deal with conflicts.

**Comment by rgenchev** [comment]
I created https://github.com/Terrastories/terrastories/pull/362 that should close this issue.
