### ISSUE TITLE
[Test] Add test for speakers_controller

### ISSUE THREAD

**Issue by MxOliver** [Terrastories/terrastories#283]
Add tests for the speakers_controller (app/controllers/speakers_controller.rb)

**Comment by rgenchev** [comment]
Can I work on this? Thanks in advance! :)

**Comment by midhunkrishna** [comment]
@rgenchev Are you working on this?

**Comment by rgenchev** [comment]
Yup :)

**Comment by rgenchev** [comment]
I created #343 that should close this issue.
