### ISSUE TITLE
[Test] Add test for the stories_controller

### ISSUE THREAD

**Issue by MxOliver** [Terrastories/terrastories#284]
Add tests for the stories_controller (`app/controllers/stories_controller.rb`)

**Comment by rgenchev** [comment]
Can I work on this? :)

**Comment by midhunkrishna** [comment]
@rgenchev Are you working on this?

**Comment by rgenchev** [comment]
Yup :)

**Comment by rgenchev** [comment]
@midhunkrishna, in order to test the controller actions, we need views. Should I create empty ones in this PR?

**Comment by rgenchev** [comment]
I created https://github.com/Terrastories/terrastories/pull/333 that should resolve this. I'd create a new issue for integrating https://github.com/paulelliott/fabrication. It'd really help when writing tests.
