### ISSUE TITLE
[Test] Add test for the speaker_story model

### ISSUE THREAD

**Issue by MxOliver** [Terrastories/terrastories#286]
Add tests for the speaker_story model (`app/models/speaker_story.rb`)

**Comment by andrewjprice** [comment]
Mind if I work on this?

**Comment by mirandawang** [comment]
@andrewjprice sorry this has been closed already. But thank you for the interest!! 

Here are some other testing tickets in case you'd like to do another :)
https://github.com/Terrastories/terrastories/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+%22%5BTest%5D%22+label%3A%22status%3A+help+wanted%22+

**Comment by andrewjprice** [comment]
> @andrewjprice sorry this has been closed already. But thank you for the interest!!
> 
> Here are some other testing tickets in case you'd like to do another :)
> https://github.com/Terrastories/terrastories/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+%22%5BTest%5D%22+label%3A%22status%3A+help+wanted%22+

Looks like all issues are taken. Never mind...
