### ISSUE TITLE
Add Projects and links to docs

### ISSUE THREAD

**Issue by kalimar** [Terrastories/terrastories#291]
To make it easier to find tickets to work on, let's create projects for each major area of expertise
Here is an [example board for Ruby on Rails issues](https://github.com/Terrastories/terrastories/projects/5)

Here's what's needed to consider this ticket complete:
- [ ] Identify the major areas of expertise (let's discuss this and signal agreement in comments below)
- [ ] Create boards and add relevant issues
- [ ] Add links to boards in the [contributing guidlines](https://github.com/Terrastories/terrastories#contributing)

**Comment by kalimar** [comment]
Areas of Expertise I can think of
* Ruby on Rails
* Cartography/Map tech
* JavaScript
* Docker
* Linux - things like NGINX setting up computers for the field

**Comment by mirandawang** [comment]
@kalimar Do we still want to use the Projects or have we switched over to Trello fully? Is there a benefit in having both?

**Comment by rudokemper** [comment]
I would suggest we keep using Projects to group together related issues. I just updated the bug squashing Project to be able to link to all of the bug tickets in the Wiki Roadmap.

cc @FeminismIsAwesome
