### ISSUE TITLE
Execute bundle and rails db:migrate on docker-compose up

### ISSUE THREAD

**Issue by namel3ss** [Terrastories/terrastories#296]
When there are new gems added to the app or pending migrations, it is a lot more easier to just stop the composer and up it again. We can add the `bundle` and `rails db:migrare` commands to the composer. 

Reason for this suggestion is the following issue:

I stopped the container and there was a new gem. I couldn’t run the container with `docker-compose up` anymore because rails -s was failing.

**Comment by mirandawang** [comment]
Thanks for the suggestion, I agree this would be helpful! It can be tedious to have to re-run `docker-compose build` every time.

**Comment by mirandawang** [comment]
We've talked about building an image for the container that's hosted on DockerHub, but maybe this would be a good interim solution? What do you think? @kalimar @robbkidd

**Comment by kalimar** [comment]
@namel3ss can you start work on it and we can test it on our computers see where we get?

**Comment by namel3ss** [comment]
@kalimar I can put a merge request instantly. Already have it locally for me ;)
