### ISSUE TITLE
Setting-up RuboCop and Eslint

### ISSUE THREAD

**Issue by midhunkrishna** [Terrastories/terrastories#299]
I noticed that we don't have linters setup for Ruby and Javascript. Following, is my suggestion:
 
#### Setup RuboCop for Ruby
- We can add RuboCop for Ruby and integrate https://github.com/github/rubocop-github

#### Setup Eslint for Js
- We can setup eslint and similar to the above case, can integrate something like https://www.npmjs.com/package/eslint-config-airbnb

To go a step further, we can add husky hooks to run all the linters as recommit hooks.

**Comment by namel3ss** [comment]
I vote for that as well. Would suggest to discuss what works best for everyone, because the default config of rubocop is too strict in some cases IMO. Also would advise to start applying it only on new  changes as a starter, and apply it everywhere once there are not so many PR open.

**Comment by mirandawang** [comment]
I think this would be a great addition to the codebase. Agreed on discussing which rules we should enforce, and applying it only on new changes to start sounds like a solid idea. Thanks for the suggestions!!

**Comment by kalimar** [comment]
Sounds like a plan. I'm going to break  this out into two separate issues.
