### ISSUE TITLE
Time for Javascript coverage too!

### ISSUE THREAD

**Issue by kalimar** [Terrastories/terrastories#311]
In the spirit of https://github.com/Terrastories/terrastories/issues/276 - let's add javascript tests too.

- [ ] Setup jest testing framework - one ticket
- [ ] setup istanbul test coverage tool - one ticket
- [ ] Add Javascript tests - these will be individual tickets.

The goal with this is to get everything ready for running continuous deployment with [Travis CI](https://travis-ci.com)

**Comment by gabsprates** [comment]
@kalimar, can i take this tasks?

**Comment by gabsprates** [comment]
@kalimar, actually, I saw you already have Jest and Coverage config on [`package.json`](https://github.com/Terrastories/terrastories/blob/master/package.json#L25) file.
Jest uses Istanbul, so looks like you can check the 1st and 2nd items of it's issue.

**Comment by kalimar** [comment]
Oh dang @gabsprates thanks for noticing that. One of our earlier contributors must have done this. I'll add the tests in a couple of days then. Sorry for the confusion.

**Comment by kalimar** [comment]
I should have done a bit more homework here before creating this ticket. I'm moving these notes over to a milestone and clarifying the requirements. https://github.com/Terrastories/terrastories/milestone/7
