### ISSUE TITLE
[Tests] Setup ESLint for Javascript

### ISSUE THREAD

**Issue by kalimar** [Terrastories/terrastories#314]
We are going to setup [ESLint](https://eslint.org/) as part of our development environment. This will involve some additional documentation so developers know how to integrate the tool into their text editors.

Before merging this we should come to a basic agreement on configuration and local setup.

- [ ]  Setup [ESLint](https://eslint.org/)
- [ ]  Configure [ESLint](https://eslint.org/docs/user-guide/configuring)
- [ ] Add documentation for developers to integrate with text editor

**Comment by estevam31** [comment]
can I work on this?

**Comment by kalimar** [comment]
@estevam31 Yeah definitely. If you don't mind, please add comments here about the configuration you have in mind. I suspect folks will want to discuss before we enforce them. 

Thanks for contributing

**Comment by estevam31** [comment]
I think the best for the project is to use the airbnb standard with some modifications, I'll see how the project behaves. Let me know if you have any suggestions.

**Comment by kalimar** [comment]
Great. Let's start with that and then we can test it locally.

**Comment by estevam31** [comment]
I'm quite busy these days, if anyone with more free time is able to do this and send a PR before me, it's better for the project. But still count on me.

**Comment by midhunkrishna** [comment]
@estevam31 @kalimar I can pick this up. 👍
