### ISSUE TITLE
[Tests] Setup Jest testing framework

### ISSUE THREAD

**Issue by kalimar** [Terrastories/terrastories#318]
https://jestjs.io/

**Comment by sowmiyamuthuraman** [comment]
can i work on this?

**Comment by sowmiyamuthuraman** [comment]
can i work on this?

**Comment by mirandawang** [comment]
@sowmiyamuthuraman Are you still interested in working on this? We would love your help!

**Comment by kalimar** [comment]
@sowmiyamuthuraman We added some additional notes here https://github.com/Terrastories/terrastories/milestone/7
Apologies for the vague early tickets here. For completeness, we'll want to add documentation on how to run tests and add at least one test to confirm everything works. Please let us know if you have any questions.

**Comment by sowmiyamuthuraman** [comment]
@kalimar there is already a setup specified for jest in package.json.
`"jest": {
    "setupFiles": [
      "<rootDir>/spec/javascript/i18n-mock.js"
    ],
    "roots": [
      "spec/javascript"
    ],
    "collectCoverage": true,
    "coverageDirectory": "spec/javascript/coverage",
    "collectCoverageFrom": [
      "**/*.{js,jsx}",
      "!**/node_modules/**",
      "!**/spec/javascript/coverage/**"
    ],
    "moduleDirectories": [
      "node_modules"
    ]
  }`

but I couldn't find any javascript/i18n-mock.js file in the spec folder? can you please help me with this?

**Comment by kalimar** [comment]
@sowmiyamuthuraman you can assume those settings are incorrect, they carried over from our old development environment. No one added mocks yet either. My plan was to try some of the options from the i18n docs https://react.i18next.com/misc/testing. Let me know if that helps.
