### ISSUE TITLE
[Demo] Add images to the seed data

### ISSUE THREAD

**Issue by mirandawang** [Terrastories/terrastories#353]
Let's find some fun fake images that we can use for the seed data.

Images will need to be added to the repo and put into the assets directory.

Add one speaker photo for each speaker and a Place photo for each place in the seed data.

**Comment by rudokemper** [comment]
Oh! I like this :)
And maybe short video clips that won't eat up too much space on Github? Just to show that the video functionality is working, like on the Heroku demo instance.

**Comment by henriquepjv** [comment]
Hi @mirandawang, may I help you with this task?

**Comment by rudokemper** [comment]
Definiely, @henriquepjv, please feel free to do so :)

**Comment by henriquepjv** [comment]
Great!! It's done :tada:

**Comment by rudokemper** [comment]
Thanks @henriquepjv! I left one comment on that PR. Also, if you'd like to take on a related ticket, I just filed that here 😃: https://github.com/Terrastories/terrastories/issues/367
