### ISSUE TITLE
[Map] Reset the search filters 

### ISSUE THREAD

**Issue by kalimar** [Terrastories/terrastories#364]
@leosoaivan noticed that search filters don't clear when you close a pop-up. 

We want to rewrite `filter.jsx` to be a functional component and follow [one of these patterns](https://reactjs.org/blog/2018/06/07/you-probably-dont-need-derived-state.html#preferred-solutions) of which we can discuss the pros and cons in the comments below.

**Comment by neckenth** [comment]
@kalimar I'd like to give this a shot. Can you assign me?

**Comment by kalimar** [comment]
Woot! Go for it!

**Comment by neckenth** [comment]
@kalimar I just started this - I was able to change `Filter` from a class-based component to a functional component, as requested.

Here's a link to this component on my fork for your reference: https://github.com/neckenth/terrastories/blob/neckenth/364/clear-filters-upon-close/app/javascript/components/Filter.jsx

Would love to discuss your recommendation for the pattern you'd like to follow for clearing the filters.

**Comment by matthewcm** [comment]
I'll get on this issue :)

**Comment by neckenth** [comment]
@kalimar I gave this a shot and opened a PR for my solution. If you want to handle component state in a different way, please let me know.

**Comment by kalimar** [comment]
@neckenth thank you. Sorry I couldn't be a little more proactive there. I'll review the PR today. Your help is much appreciated.
