### ISSUE TITLE
Setup Linting Script

### ISSUE THREAD

**Issue by MxOliver** [Terrastories/terrastories#371]
Set up the `package.json` with a script that will run the linter on all files in the command line based on the configuration file. This will ensure that code is compliant before pushing it to GitHub. 

The script should be called with something like `yarn lint` or `npm lint` and allow the browser to read from the linter configuration file and give you live linting feedback while editing your code.

**Comment by mirandawang** [comment]
Closing this for now since I think it's resolved?
