### ISSUE TITLE
"Run Yarn twice" bug

### ISSUE THREAD

**Issue by kalimar** [Terrastories/terrastories#372]
Our [documentation](https://github.com/Terrastories/terrastories/blob/master/SETUP.md#setup-and-running-the-server) currently recommends running `docker-compose build` as well as `docker-compose run web yarn install`. This shouldn't be needed because `yarn install` is built into the `build` script.  

This ticket requires researching the root cause of the issue and providing a solution that works on all three operating systems: Windows, macOS, and Linux.

**Comment by anusha5695** [comment]
I @kalimar : I will like to look into this

**Comment by wulffeld** [comment]
@anusha5695 Just starting out with terrastories and hit this problem. I think it's because public/packs is versioned. Removing public/packs and it works like a charm.

**Comment by kalimar** [comment]
Great news. We'll cut another ticket to clean up the docs for people not to run things twice.

**Comment by wulffeld** [comment]
@anusha5695 Are you still interested in this ticket? Otherwise I'll be happy to fix it.

**Comment by kalimar** [comment]
@anusha5695 Thanks for considering the ticket. We can definitely find you some more issues in around node modules if you are interested. @wulffeld found a solution and is going to submit a PR.
