### ISSUE TITLE
Putting the list of languages in alphabetical order A-Z

### ISSUE THREAD

**Issue by rudokemper** [Terrastories/terrastories#379]
Currently, the list of available languages in Terrastories (provided via the i18n gem) is in a non-alphabetical order.

For example, on the Heroku build (http://terrastories.herokuapp.com/), the current order is `EN (default), PT, JA, ES, NL`. With these available languages, the order should be `EN (default), ES, JA, NL, PT`.

(Note that the default doesn't need to be first, although it happens to be in the above example. If we had Arabic (AR) as an available language, that should precede `EN (default)`).

Let's alphabetize the list of languages in a A-Z order.

**Comment by agustinariq** [comment]
Hello! Can I try this one?

This should be the preferred order

> AR, EN (default), ES, JA, NL, PT.

And not this

> EN (default), AR, ES, JA, NL, PT.

right?
