### ISSUE TITLE
[Convenience] Create a script to generate data for development purposes

### ISSUE THREAD

**Issue by mirandawang** [Terrastories/terrastories#390]
Currently, we only have a few dummy stories and points set up in the `seeds.rb` file, whereas the community use cases have hundreds of different Stories, Places, and Speakers and hours of video footage. It would be great if we could have a similar amount of data in the app for development purposes. For this issue, let’s write a script that can generate a hundred or so different pieces of data including Stories, Places, and Speakers, with media fields and relationships. Bonus points for a script that can take arguments about how much to create!

We would like this script to be able to be run with a docker command and it would create records into the Rails database. Please also include some updates to the SETUP guide with instructions on how to use the script.

**Comment by MxOliver** [comment]
I'd like to work on this!
