### ISSUE TITLE
[CMS] Add media file hosted elsewhere (such as YouTube, Vimeo, Soundcloud)

### ISSUE THREAD

**Issue by rudokemper** [Terrastories/terrastories#404]
Currently, we can add media content (video, audio, images) to `Places`, `Stories`, and `Speakers` by uploading them directly to Terrastories.

For online instances of Terrastories, we should make it possible to embed media content hosted elsewhere by adding an `Insert from URL` option.

It might also be necessary to add a special option for embedding from popular platforms such as YouTube and Vimeo.

It should be sufficient to paste in the URL of the source (much like the WordPress media library), but we open to other possibilities. @rudokemper is available to pair on this for at technical spike over the Ruby by the Bay weekend.

**Comment by Lukmin1999** [comment]
Katherine, Oliver and I would like to assist with this issue!

**Comment by kathenry** [comment]
Yes!
