### ISSUE TITLE
[CMS] Split up 'Name' into 'First Name' and 'Last Name' in the Speaker model

### ISSUE THREAD

**Issue by rudokemper** [Terrastories/terrastories#405]
Currently, the `speaker` model has a singular `name` field. We should have `first_name` and `last_name` so we can sort by last name, among other things.

**Comment by GQuirino** [comment]
can i take a look on this issue?

**Comment by rudokemper** [comment]
@GQuirino thanks for offering, but we actually meant to take this particular story down after discussing it some more. Sorry about that, but please feel free to check out any of our other open issues :)
