### ISSUE TITLE
[CMS] Adjust required/optional fields in Stories model

### ISSUE THREAD

**Issue by rudokemper** [Terrastories/terrastories#406]
In the `stories` model, let's:

* Set `interviewer_id` and `interview_location_id` to optional.
* Set `speaker_id` field to required.

**Comment by rudokemper** [comment]
Quick comment: I'm not sure if it's `speaker_id` or something else; but, in the Administrate back end, it's letting the user add stories without a speaker, and that shouldn't be the case.

**Comment by FeminismIsAwesome** [comment]
Resolved by 145ae99
