### ISSUE TITLE
[Import/export] Document CSV importer format in Administrate

### ISSUE THREAD

**Issue by bhaibel** [Terrastories/terrastories#420]
The CSV importer's format is not documented in the UI, which leads to user confusion as to how they ought to make a test CSV.

**Comment by slaloggia** [comment]
Currently, the system is expecting a csv with column headings and is matching the values to attributes by location, not by the heading name. So names do not have to be exact, but the order matters.

- Title 

- Description 

- Speakers (if multiple, separate with commas)

- Places (if multiple, separate with commas)

- Interview_location 

- Date_interviewed 

- Interviewer 

- Language 

- Media  (this field currently cannot be empty, should that be the case?)

- Permission_level (leave blank if no restrictions, ANYTHING in this column will set permission level to "user_only")
