### ISSUE TITLE
SETUP.md readme is missing one additional step for Windows

### ISSUE THREAD

**Issue by rudokemper** [Terrastories/terrastories#438]
The command `docker-compose exec web bin/setup` does not work in Windows if you don't run the following command first: `docker exec terrastories_web_1 /bin/bash`.

**Comment by rudokemper** [comment]
@lauramosher or @kathenry -- did you run into this issues on your Windows builds of Terrastories as well? I'll try to install the latest build of Terrastories fresh on my Windows machine tomorrow, and if we don't need to input `docker exec terrastories_web_1 /bin/bash` anymore, I'll close this issue and withdraw my PR.

(cc @FeminismIsAwesome)

**Comment by lauramosher** [comment]
@rudokemper I have not needed to run this!

**Comment by rudokemper** [comment]
I can confirm that it's (no longer?) necessary working with a fresh build of master. Closing this issue and PR.
