### ISSUE TITLE
[CMS] Images uploaded to a story currently render as an audio file in the sidebar

### ISSUE THREAD

**Issue by rudokemper** [Terrastories/terrastories#441]
Currently, it is possible to upload an image to a story. This is desirable behavior.

However, images are currently incorrectly rendering as an audio file in the sidebar. It should render as an image.

In the below screenshot, there is an image added for this story, not an audio file.

![image](https://user-images.githubusercontent.com/31662219/83903788-c09aee00-a72c-11ea-996c-adf7f6506858.png)

**Comment by Lukmin1999** [comment]
Looking through the code, I believe the problem lies in StoryMedia.jsx. Specifically in the render method, there are only two rendering options: video or audio. If it is not of type video, the media is automatically assigned that of type audio.
