### ISSUE TITLE
[CMS] Prevent users from entering values outside of the threshold values for Place lat/long fields

### ISSUE THREAD

**Issue by rudokemper** [Terrastories/terrastories#442]
Currently, it is possible to enter a value for the `lat` field that exceeds the boundaries of -90 to 90, and -180 to 190 for the `long` field.

This consequently breaks the map when you return to the home view.

An error message should pop up in Administrate when a user tries to enter values outside of the treshholds for the `Latitude` and ` Longitude` fields.

**Comment by Lukmin1999** [comment]
I could tackle this one.
