### ISSUE TITLE
[CMS] [i18n] Language picker should show selected language, not default language.

### ISSUE THREAD

**Issue by rudokemper** [Terrastories/terrastories#446]
Currently, the language picker (on the Welcome/Home) screen is showing a language as `(default)`. Moreover, this `(default)` text is added independent of which language is actually selected as the default, in line 4 in the file `application_helper.rb`.

We should get rid of the `(default)` text altogether since that is not so interesting from a user point of view. Instead, we should have `(selected)` text showing for the language that is currently selected.

(As a follow up ticket, we can add the word `selected` to all of the i18n languages currently in Terrastories.)

**Comment by ohamuy** [comment]
Our team (Katherine, Oliver, and Lucas) will claim this!

**Comment by Lukmin1999** [comment]
I am part of Oliver's team!

**Comment by kathenry** [comment]
Me too!

**Comment by lauramosher** [comment]
@rudokemper do you want to write a new ticket to translate the last few languages or keep this one open?
