### ISSUE TITLE
Minor adjustment to image rendering in the marker pop ups

### ISSUE THREAD

**Issue by rudokemper** [Terrastories/terrastories#469]
Let's make the photo fill the full width of the pop up, instead of floating to the left of the text fields (as in the below screenshot). The text can go underneath the image. Let's also ensure that image proportions are respected, not shrunk as below.

![image](https://user-images.githubusercontent.com/31662219/87341238-4887cb00-c517-11ea-8412-724b22932ed3.png)

Current pop up photo rendering can be seen on the live demo: http://terrastories.herokuapp.com/en/home

Related follow up issue: https://github.com/Terrastories/terrastories/issues/350

**Comment by ohamuy** [comment]
I can do this!

**Comment by ohamuy** [comment]
I have already solved this problem if I can claim it!

**Comment by rudokemper** [comment]
@ohamuy assigned!
