### ISSUE TITLE
[UI] Scroll bar not rendering properly in Chrome (Windows)

### ISSUE THREAD

**Issue by rudokemper** [Terrastories/terrastories#470]
In Chrome, the sidebar scroll bar is not rendering as it should. It doesn't adapt to the full height of the overflow content.

![image](https://user-images.githubusercontent.com/31662219/87346665-f4cdaf80-c51f-11ea-8b5e-4e13e3e13b45.png)

By contrast, it does render properly on Firefox, same computer.

![image](https://user-images.githubusercontent.com/31662219/87346736-0c0c9d00-c520-11ea-96dd-425d4a875944.png)

This issue has been observed on various Windows machines.

**Comment by kathenry** [comment]
I am running the heroku app using chrome on Windows and my scroll bar doesn't appear to have the same issue, is this issue resolved for the heroku app version?

**Comment by rudokemper** [comment]
I just checked this. So, I can confirm the issue on Chrome on my Surface Pro 7 (Windows 10 Home) using the Heroku App version.

But, I don't see it on Chrome on a Dell Inspiron 15 7000 (Windows 10 Pro).

Same version of Chrome (Version 83.0.4103.116).

**Comment by kathenry** [comment]
@rudokemper I don't seem to have this issue on my windows both using and not using Heroku, and I also have Windows 10 Home. Maybe it has to do with the Surface and how the code is translated for that interface?

**Comment by mirandawang** [comment]
Resolved here! 8c7546a628e02c89c1a1eae9d1a2484650f917a3
