### ISSUE TITLE
Changes to marker popup layout and content

### ISSUE THREAD

**Issue by rudokemper** [Terrastories/terrastories#472]
Currently, the marker popups are showing only the `Region` and `Type of place` fields. We should have `Description` included from the Place model as well, as well and lay it all out in the following fashion:

`Image` (100% width as per Oliver's PR already in submission)

`Description` (with some top and bottom padding to create space between the images and the other two text fields)

**Type of place** (text retrieved from i18n): `type of place`
**Region** (text retrieved from i18n): `region`

**Comment by ohamuy** [comment]
I can complete this!

**Comment by ohamuy** [comment]
Just to clear it up, do you want the description of the place to be displayed or the description of the story to be shown? I

**Comment by ohamuy** [comment]
I completed the issue, I am just wondering which version you like better: 
<img width="263" alt="Screen Shot 2020-07-17 at 3 19 53 PM" src="https://user-images.githubusercontent.com/46689344/87835161-340e4000-c841-11ea-9a9b-02fc0911f2f6.png">
<img width="263" alt="Screen Shot 2020-07-17 at 3 20 31 PM" src="https://user-images.githubusercontent.com/46689344/87835166-37093080-c841-11ea-8881-dbc3a1d1f596.png">

**Comment by rudokemper** [comment]
Hi @ohamuy, looks great! I favor the second version. Can we also have slightly more top and bottom padding on the description text, let's say 5px? Thanks so much!

**Comment by ohamuy** [comment]
Ok, so you wrote another issue #473, which kind of conflicts with the stuff this issue solves. Would you like it to be full sentences or in the format you see above in the second picture? I personally prefer this format above as it is easier to digest than a sentence.

**Comment by rudokemper** [comment]
Fair point -- sorry if I wasn't clear with these issues. I was thinking that for this issue #472, we're just worrying about the photo and the description and essentially leaving the metadata fields alone, but I see that we're doing some bolding here to enhance the legibility of the metadata fields.

I was thinking of issue #473 as the next step, treating the metadata by displaying the information in a sentence format.

As for the legibility, that's an interesting discussion in the tech for indigenous communities space. We tend to veer towards using full sentences as often as possible, because some indigenous peoples, particularly elders, are not used to seeing information presented in that format. But let me give it some thought, because you're right that some communities might prefer the format above. Perhaps we could provide both options? I'll close to issue for now.
