### ISSUE TITLE
[Tests] Improve model specs for Speaker

### ISSUE THREAD

**Issue by slaloggia** [Terrastories/terrastories#492]
Should test associations, validations, and methods (see story or place specs for example of .import_csv method tests)

**Comment by GQuirino** [comment]
i'll take that issue :smile:

**Comment by mirandawang** [comment]
@GQuirino Thank you!

**Comment by mirandawang** [comment]
Merged in here! 83c5b51b34d1b07389b7c8afb08eb8810ac16653
