### ISSUE TITLE
[Tests] Install Jest framework test command and add a React component test

### ISSUE THREAD

**Issue by FeminismIsAwesome** [Terrastories/terrastories#494]
We would like more confidence, especially with desires to update the UI and add new map-facing features, that the javascript is rendering as expected.

Let's do this by adding a Jest framework https://medium.com/@kylefox/how-to-setup-javascript-testing-in-rails-5-1-with-webpacker-and-jest-ef7130a4c08e

Let's also add Enzyme (https://enzymejs.github.io/enzyme/) to better test our React components.

Acceptance Criteria: one added React test run by running yarn test, that runs an Enzyme component test. Preferably against a current model but could also be a demo react component test.

**Comment by mirandawang** [comment]
Closed here I believe! f503dd14ef85de83d4ae2c962e4427cff132d5fd
