### ISSUE TITLE
[React] Create an introductory panel before displaying the StoryList in StoryMap

### ISSUE THREAD

**Issue by mirandawang** [Terrastories/terrastories#507]
Currently, when a user enters the StoryMap, the StoryList in the sidebar is displayed immediately. There is a card on the right side of the screen that pops up and explains a bit about the terrastories app.

Let’s update the UI so that there is no more card and instead, we display an introductory panel in the sidebar before we display the list of Stories.

See below for the design.
![Screen Shot 2020-09-03 at 5 46 06 PM](https://user-images.githubusercontent.com/8590508/92176889-641f9b80-ee0d-11ea-8bfb-afc72bda2b61.png)

note: copy change from this design -- Let's end the explore text at "all over" and not make it specific to the Matawai

We’ll likely need to create a new component which will be rendered into the Sidebar. Then the Sidebar will conditionally display this panel or the list. The condition can be based on some component state which determines whether or not the “Explore” button on this screen has been clicked in this session.

Acceptance Criteria:
When a user goes to view the Story Map, they should see the introductory panel before they see the Stories.
The user should not see the introductory panel after clicking the “Explore” button and should only see Stories.
If the user refreshes the page, the introductory panel will be back. 
The card on the right of the screen is fully deleted.

Bonus points: Add Jest tests

**Comment by Julien-Bidar** [comment]
Hi, if it's ok with you I'd like to work on this issue.

**Comment by rudokemper** [comment]
Certainly - I will assign it :)
