### ISSUE TITLE
[Tests] Test CurriculumStory model

### ISSUE THREAD

**Issue by rgenchev** [Terrastories/terrastories#524]
I noticed that there aren't any tests for `CurriculumStory` model. I'd like to add some. Can I work on this?

**Comment by mirandawang** [comment]
@rgenchev You are totally welcome to!

**Comment by mirandawang** [comment]
@rgenchev I believe this is a duplicate of https://github.com/Terrastories/terrastories/issues/491 , I'll assign you over there! Thanks!
