### ISSUE TITLE
[Rails][Administrate] Add CSV importer format in Administrate UI

### ISSUE THREAD

**Issue by mirandawang** [Terrastories/terrastories#543]
For Places, Stories, and Speakers, admin are able to upload a CSV to bulk import data. However, it’s not clear what format the CSV needs to be in for the importer. Let’s add some UI to each of the admin pages that describes the necessary CSV format.

Sample CSV file: https://drive.google.com/file/d/1Ir6TC5THEoQKk-98JZ5KpTjXd-R6yMmA/view

Administrate view for the importer can be found [here](https://github.com/Terrastories/terrastories/blob/master/rails/app/views/admin/application/index.html.erb#L69)

Acceptance Criteria:
For the Place importer, the CSV format is described next to the import field.
For the Speaker importer, the CSV format is described next to the import field.
For the Story importer, the CSV format is described next to the import field.

Design is up to you! Please add where you think would make the most sense. :) 

from @slaloggia (Thank you!):
Currently, the system is expecting a csv with column headings and is matching the values to attributes by location, not by the heading name. So names do not have to be exact, but the order matters.

Title
Description
Speakers (if multiple, separate with commas)
Places (if multiple, separate with commas)
Interview_location
Date_interviewed
Interviewer
Language
Media (this field currently cannot be empty, see #534 #535 #536)
Permission_level (leave blank if no restrictions, ANYTHING in this column will set permission level to "user_only")

**Comment by Aliciawyse** [comment]
If this is still up for grabs, I'd like to give it a shot!
