### ISSUE TITLE
[Rails][Administrate] Let's set the default background for Themes if a user doesn't upload one

### ISSUE THREAD

**Issue by rudokemper** [Terrastories/terrastories#552]
## Context:
We are building a Theme Builder that makes it possible for users to control thematic elements of Terrastories from within Administrate. It is possible to change the background of the welcome page using this feature. 

However, currently when a user creates a theme, and does not upload a new background image, the welcome page background renders as blank (white). The expected behavior is that the default background image (`welcome-bg.jpg` in `/assets`) stays the same.

## Acceptance criteria:
[] User creates a new theme
[] User does not upload a new background image
[] User activates the theme
[] User loads Terrastories and goes to welcome page `/`
[] The background image is still `welcome-bg.jpg` instead of nothing.

**Comment by tauhir** [comment]
Hopefully its fine, but I've made a PR for this (#556) because I could fix it when doing issue #553.
