### ISSUE TITLE
[Rails][Administrate] Let's make a Theme that comes bundled with Terrastories and is activated by default

### ISSUE THREAD

**Issue by rudokemper** [Terrastories/terrastories#553]
## Context:
We are building a Theme Builder that makes it possible for users to control thematic elements of Terrastories from within Administrate.

Currently, when you load Terrastories, there are a few default assets, such as `welcome-bg.jpg` as background for the welcome screen and `rubyforgood.png` as the first logo. However, these are not selected as a Theme. `welcome-bg.jpg` is the standard choice for a background image in the absence of a theme, and the `rubyforgood.png` logo is coded to always be present as the first logo.

Let's instead make these two assets into a Theme that comes bundled with Terrastories, and have this Theme be activated by default. 

## Acceptance criteria:
[] A new theme is created and comes bundled with Terrastories.
[] Theme contains the current standard assets (`rubyforgood.png` as first logo and `welcome-bg.jpg` as background)
[] This theme is selected by default.
[] It is possible to create a new theme with a different background and logos (`rubyforgood.png` should not always be present and unchangeable as the first logo, as it currently is.)
[] Once a new theme has been created, it is possible to deactivate that new theme and reactivate this first default theme.
[] Existing tests do not break

**Comment by tauhir** [comment]
@rudokemper can I pick this up?

**Comment by rudokemper** [comment]
Sure! @tauhir I will assign you :)
