### ISSUE TITLE
[Bug] On StoryList, selecting an option in the 2nd filter after clearing the 1st filter causes browser crash

### ISSUE THREAD

**Issue by leosoaivan** [Terrastories/terrastories#564]
**Describe the bug**
When filtering and selecting options to view cards, certain interactions can cause the browser to crash locally.

**To Reproduce**

1. Click on first filter, and select any option
2. Clear option
3. Click on second filter, and select any option
4. Crash

**Expected behavior**
Clearing the first filter also clears the second filter, so that no option is clickable.

**Desktop (please complete the following information):**
 - OS: Win10
 - Browser: Firefox
 - Version: 83.0

**Comment by Julien-Bidar** [comment]
Hello everybody,
I just did a pull request to fix this bug

**Comment by rudokemper** [comment]
Thanks, @Julien-Bidar!
