### ISSUE TITLE
[Rails] Move RFG logo to main login screen, and remove it from sponsor logos on welcome screen once logged in

### ISSUE THREAD

**Issue by rudokemper** [Terrastories/terrastories#582]
Currently, the Ruby for Good logo and preceding "Built with <3 by" text shows up once a user has logged into a Terrastories community instance and accesses the welcome page. These should be showing for the log in (devise) screen instead, and removed from the welcome page. The welcome page should only show sponsor logos that have been defined in Themes (as is currently operational, but the sponsor logos are added after the RFG logo which is always there by default).

## Acceptance criteria:
[] I load Terrastories without having been signed in, and access to devise log in page.
[] Below the sign in box, I see the "built with <3 by" text and Ruby for Good logo, styled to fit to the window responsively.
[] I log in, and access the Welcome page.
[] Below the box, I don't see the "built with <3 by" text and Ruby for Good logo; I only see either sponsor logos defined by the community's theme, or nothing if there are none set in the theme.

## Assets
Let's remove "Built with <3 by" text and Ruby for Good logo from here
![image](https://user-images.githubusercontent.com/31662219/103092168-637d6180-45c4-11eb-9b20-88ee27bb512b.png)

And place it here, but smaller
![image](https://user-images.githubusercontent.com/31662219/103092203-84de4d80-45c4-11eb-889f-bb5f84e112aa.png)

**Comment by astojanowski** [comment]
I'd like to work on this.
