### ISSUE TITLE
[CRITICAL] add ENV parameter to disable multi-instance

### ISSUE THREAD

**Issue by rudokemper** [Terrastories/terrastories#586]
## Context:
We have recently set up Terrastories as multi-instance permitting multiple communities to use one Terrastories server. This is a great asset for online setup of the application as with the https://our.terrastories.io server, but in some cases, it may be better to only have one community set up on Terrastories. For example, in an offline context where only one community is accessing Terrastories on a mini-computer, or for online servers serving only one community. Here, it is unnecessary and even undesirable to ask users to have to log in every time.

For these use cases, we can reproduce how Terrastories used to function -- anyone can freely enter the site and check out the map as an anonymous user, but you won't see any restricted stories. (This is how Terrastories used to work, and in terms of permissions, this is what `viewer` users are able to see in the multi-instance architecture.)

Let's reproduce that functionality as an option for these use cases. Let's add an optional parameter in the `.ENV` file, `MULTI_INSTANCE="disabled"`. Then, when the user first builds Terrastories, it will create a singular community database by default, and always allow anonymous users to enter the site without logging in.

## Acceptance criteria:
- [ ] Before building Terrastories, I edit `.ENV` and add a parameter `MULTI_INSTANCE="disabled"`.
- [ ] I then build Terrastories (`docker-compose build`, `run`, etc.)
- [ ] When I visit my Terrastories build, I am not forced to log in directly via devise, but instead can access the welcome screen and enter as an anonymous user (with permissions akin to `viewer` in multi-instance currently).
- [ ] I can also still log in with usernames with `viewer`, `editor`, or `admin` permissions.

## Assets
An example of the welcome screen / login setup prior to multi-instance, which can be reproduced using this .ENV variable.:
![image](https://user-images.githubusercontent.com/31662219/103094244-e2759880-45ca-11eb-96c7-815ffe1b5db8.png)

**Comment by rudokemper** [comment]
@lauramosher did I get this right?

**Comment by lauramosher** [comment]
Yes, this looks like an accurate assessment of what we want to do!
