### ISSUE TITLE
[Rails] Create a "topic" field for story and add it to Administrate views and sidebar filter

### ISSUE THREAD

**Issue by rudokemper** [Terrastories/terrastories#588]
## Context:
Some communities have told us that they would like to see a "Topic" field to be able to filter through stories. Let's 

1) do a migration to add this field to the `Story` model
2) add it to the Administrate views for viewing and editing stories (as a typeahead field).
3) add it as a filter option in the first dropdown on the map view.

## Acceptance criteria:
[] When an admin user logs in to the Administrate back end, and opens a story, `Topics` is shown as a block on the sidebar (similar to `Description`).
[] When the admin user edits a story, `Topics` shows up as a typeahead field under `Language`. 
[] When any user visits the map, `Topics` is one of the dropdown options in the first dropdown of `Filter stories` if there are stories with a non-empty topic field. 
[] The second dropdown will be populated with the values provided for `Topics` in the stories. When selecting a topic, the sidebar and map filters the stories & associated markers, as per the standard filtering behavior.
[] Existing tests do not break

**Comment by julinvictus** [comment]
I can give it a try to this one

**Comment by julinvictus** [comment]
Done✅
