### ISSUE TITLE
[Bug][Map] Sidebar filters dropdown are not filtering Places on the map.

### ISSUE THREAD

**Issue by rudokemper** [Terrastories/terrastories#597]
**Describe the bug**
The filter dropdowns in the Terrastories sidebar are supposed to do a few things: 

Filter the stories in the sidebar,
Zoom to the maximum extent of the Places with filtered stories,
Hide Place markers on the map that don't have a story in the active filter.

Currently, this last step is not working. 

**To Reproduce**
Steps to reproduce the behavior (this is one example):
1. Use one of the dropdown filters.
2. It will zoom to the maximum extent of the Place markers.
3. Navigate the map to where there were other Place markers that should have been filtered out. You will still see them show up.

**Expected behavior**
The only Place markers on the map that should show up are Places that have a Story in the sidebar. (I.e. if there are 100 places in Terrastories, and an active filter is only showing stories for 25 places, only those 25 Place markers are shown).

**Additional context**
This demo, running a November 2020 version of the Terrastories codebase, does have the behavior as desired working. http://terrastories-2020imw.herokuapp.com/

**Comment by rudokemper** [comment]
@lauramosher I think this may have come up during the December Tech Matters work. Because the filters were operating just fine in November.

**Comment by lauramosher** [comment]
@rudokemper I looked into this — the filter logic is all encompassed in the React code; not the rails code. This was likely accidentally introduced when we merged the new Map + Marker components since it changed how we update the markers on filtering.

See: https://github.com/Terrastories/terrastories/pull/563

Updating the labels. @mirandawang Do you have time to look into this?

**Comment by rudokemper** [comment]
Yeah, my mistake on this -- I thought that the November 2020 Heroku demo above was using a version of the codebase with the map marker refactoring work already done, but that is not the case. That took place shortly after IMW and before the TM work. Was getting my timelines confused :)

**Comment by rudokemper** [comment]
That's great! Thanks @astojanowski I just assigned it to you.

**Comment by astojanowski** [comment]
Fixed by updating map markers source every time the list of places has changed. Additionally I removed duplicates from the list of points, couldn't find any use of these duplicates...
