### ISSUE TITLE
[Bug][React] When a map Marker popup expands in size to accommodate an image, the X to close the popup stays where it was

### ISSUE THREAD

**Issue by rudokemper** [Terrastories/terrastories#600]
**Describe the bug**
In Terrastories, it is possible to add an image for a Place marker. This gets visualized in the marker popup, when a user clicks on a Place marker point on the map.

If there is an image for a place, the popup expands in size to accommodate the image. But the X to close the popup stays where it was, in the original popup dimensions.

**To Reproduce**
1. Add an image for a place.
2. Go to the map and click on the place to open the popup.
3.  See how the popup first loads as though there was no image, it then expands to include the image, but the X will stay where it was before the expansion.

**Expected behavior**
When the popup expands, the X to close the popup also adjusts to be in the top right of the popup.

**Screenshots**
![image](https://user-images.githubusercontent.com/31662219/106526868-594c5e00-64b4-11eb-8799-cf2e3bd0007f.png)

**Comment by astojanowski** [comment]
Hi! I have fixed this bug.

**Comment by rudokemper** [comment]
Thanks so much @astojanowski!

**Comment by astojanowski** [comment]
I'm glad to help :)
