### ISSUE TITLE
[Bug][Rails] Updating Theme fields causes map to not load

### ISSUE THREAD

**Issue by rudokemper** [Terrastories/terrastories#603]
**Describe the bug**
Terrastories Theme has the ability to add a custom Mapbox map and token per community. As soon as you modify any of the other fields in the Theme (like adding a custom logo), but leave the two map fields alone, it causes the map to not work. 

**To Reproduce**
1. Go to the map with an out of the box Terrastories install. Confirm that it's working.
2. As an Admin user log in and go to the Theme menu.
3. Add a custom sponsor logo.
4. Don't do anything to the two map fields. And click Update Theme.
5. Now to go to the map. It will load blank and throw the errors in the screenshot below.

**Expected behavior**
If nothing is added to the Mapbox fields in Theme, it will just stick with the default map and key.

**Screenshots**
![image](https://user-images.githubusercontent.com/31662219/106667766-5bc3bc00-6577-11eb-8626-e72ec188758f.png)
![image](https://user-images.githubusercontent.com/31662219/106667806-6bdb9b80-6577-11eb-9392-ee696d25c3a4.png)

**Comment by rudokemper** [comment]
@lauramosher I expect this might be a bug from the December work, and an easy fix :)

**Comment by lauramosher** [comment]
Huh, I thought I tested this. I must've messed something up somewhere.
