### ISSUE TITLE
[Rails][Administrate] Change the orders of fields in the Edit view for Speakers, Stories, Places

### ISSUE THREAD

**Issue by rudokemper** [Terrastories/terrastories#652]
## Context:
Currently, the order of the fields in the Edit view for Speakers, Stories, and Places isn't the most intuitive. Let's have the fields be the following order:

`Speakers`: Name, Photo, Speaker's Community, Date of Birth, Birthplace, Stories
`Stories`: Title, Description, Topic, Media, Speakers, Places, Interview location, Interviewer, Date Interviewed, Permission level
`Places`: Name, Photo, Description, Type of Place, Region, Stories, Lat, Long

Bonus: change the field titles of Lat and Long in `Places` to "Latitude" and "Longitude"

**Comment by julinvictus** [comment]
Hi I can work on this
