### ISSUE TITLE
[Bug][Rails] Region typeahead field should only pull suggestions from active community

### ISSUE THREAD

**Issue by rudokemper** [Terrastories/terrastories#663]
**Describe the bug**
The `Region` field in the Places model is configured as a typeahead field, helpfully providing you with existing values when you add or edit this field. However, currently it is populating the list of values from _all_ of the communities on one Terrastories server, instead of just the one you are logged in to.

**To Reproduce**
1. Create or log in to a Terrastories community
2. Create some place data with the Region field filled in
3. Log out of this community, and create or log into a different Terrastories community
4. Create a place, and see the values from the first community in the suggestions for Region

**Expected behavior**
You should only see values for `Region` from the community you are logged in to.

**Screenshots**
![image](https://user-images.githubusercontent.com/31662219/136123891-20ea2496-3736-4154-bf83-d3ae1660ea25.png)
(These are all values from different communities residing on the same server).

**Comment by ConnieJChi** [comment]
👋 Hello! Do you mind if I try working on this issue?

**Comment by rudokemper** [comment]
Hello @ConnieJChi ! Welcome and thanks :)
