### ISSUE TITLE
[Bug][Rails] Null image tag displaying on popup when story card is activated

### ISSUE THREAD

**Issue by rudokemper** [Terrastories/terrastories#671]
**Describe the bug**
The popups on the map are set up to show an image, if there is one set for that place (via the `photo_url` field); if the value is null then it will not (see this code in `Popup.jsx` [here](https://github.com/Terrastories/terrastories/blob/8c53163545f64733a535cf98ebd56e63155f6775/rails/app/javascript/components/Popup.jsx#L13)).

This works when you press on a marker point on the map:

![image](https://user-images.githubusercontent.com/31662219/136293738-dae1aea1-5cde-47b0-91b6-3107f4be8bdb.png)

However, when you press on a story card in the sidebar -- which causes the map to navigate to the related Place and open up the popup -- if there is no photo, it still inserts an empty `<img>` tag.

![image](https://user-images.githubusercontent.com/31662219/136293804-653bc717-d2ce-4d14-afbb-0285f5233a21.png)

**To Reproduce**
1. Open the Terrastories map view
2. Press on a marker for a Place that does not have a photo
3. You will not see an `<img>` tag
4. Now, press on a Story that is linked to that Place
5. You will see the empty `<img>` tag in the Popup

**Expected behavior**
If there is no image in the Place `photo_url` field, it should not insert an `<img>` tag in the popup when you press a story card, much like it doesn't when you press a marker and open a popup that way.

**Comment by carlosfrodrigues** [comment]
Hi, I can take this issue!
