### ISSUE TITLE
[Rails] Change the order of options in the primary filter to alphabetical

### ISSUE THREAD

**Issue by rudokemper** [Terrastories/terrastories#672]
Let's change the order of the options in the primary filter to be alphabetical. 

So with the current selections, it would be `Region`, `Topic`, `Type of Place`, `Speaker`. If there were to be one added in the future, it would automatically be placed alphabetically as well.

(Note that the `filterMap` and `handleFilter` arrays in `App.jsx` have to be adjusted as well).

**Comment by julinvictus** [comment]
Hi I can work on this. Also I think you mean `Region, Speaker, Topic, Type of Place`

**Comment by rudokemper** [comment]
Ah you are right :) thanks @julinvictus !
