### ISSUE TITLE
[BREAKING BUG][Rails] Remove empty field choices from filters (currently crashing Terrastories); add "No Options" message if none are available

### ISSUE THREAD

**Issue by rudokemper** [Terrastories/terrastories#673]
**Describe the bug**
There are a few bugs and issues with the filters on the sidebar of the Terrastories map view.

1. If there are some empty values for the fields being filtered (Region, Topic, Type of Place, Speaker), the first choice in the second filter dropdown will be a blank option. Clicking this will crash Terrastories.
![image](https://user-images.githubusercontent.com/31662219/136296710-0b6c56ae-e766-4665-bd25-0d2a30c74423.png)

2. If there are no values whatsoever set for the fields being filtered, the second filter dropdown will show one or several blank options; clicking these will crash Terrastories.
![image](https://user-images.githubusercontent.com/31662219/132909026-7479cbb5-2c49-4801-adfa-40d9a6efe344.png)

**To Reproduce**
1. Go to Terrastories. 
2. Create (or log in to) a default community with some sample data.
3. For some of the data, make sure that one of the filtered fields (Region, Type of Place, Topic, Speaker) is empty.
3. On the map view, click on `Select Category` and chose the Filter for that field
4. See error (as per screenshot) and if you click on the empty field, it crashes the app.

**Expected behavior**

1. If there are some (but not all) empty values for the fields being filtered, there should be no empty choice option at the very beginning. Instead, the stories/places without those values will just not be accessed through that filter.
2. In the case of there not being any values set for one of the fields being filtered, instead of seeing a blank option, you would see a grayed out "No Options" message as you do when you click on the second dropdown without first having selected a category in the first dropdown.

**Comment by ConnieJChi** [comment]
👋 I'd love to take a shot at this issue!

**Comment by rudokemper** [comment]
Thanks @ConnieJChi!
