### ISSUE TITLE
[Bug] Broken Setup link on the README

### ISSUE THREAD

**Issue by ConnieJChi** [Terrastories/terrastories#678]
When clicking on the `Setup Document` link it doesn't properly link to the setup [document](https://github.com/Terrastories/terrastories/blob/master/documentation/DEVELOPMENT.md).

![Capture](https://user-images.githubusercontent.com/36419421/136323525-8d86b61b-31cc-4747-a7aa-cc99488d218b.PNG)

**Comment by toshitapandey** [comment]
Hey @rudokemper!

Apologies that I raised the pull request before confirming from you. If it's ok, please take a look at the PR.

**Comment by rudokemper** [comment]
@toshitapandey no worries! Thanks!
