### ISSUE TITLE
[Bug][Rails] Adapt height of the welcome screen card to adjust to overflow content

### ISSUE THREAD

**Issue by rudokemper** [Terrastories/terrastories#684]
**Describe the bug**
Currently, if any of the content on the welcome screen card (such as the `h1` welcome message, `.welcome-card-user`, or `.language-picker` content) is forced to go to a second line, the overall `.welcome-card` height does not adjust. Let's make it dynamically adjust so that all the content fits.

**To Reproduce**
1. Go to the Terrastories welcome screen
2. Use DevTools to make the content of any of the above adapt to two lines.

**Expected behavior**
The height of the `.welcome-card` should increase to accommodate the content needing to increase in size.

**Screenshots**
![image](https://user-images.githubusercontent.com/31662219/136832163-53334cf9-f83f-4748-8c2f-7ef530aa2dd1.png)
In this screenshot, the `.welcome-card-user` content forces the `.language-picker` content down, and while it's still visible there should be a 2em padding at the bottom as on the other sides..

![image](https://user-images.githubusercontent.com/31662219/136832036-704ce4a0-6463-44d6-9097-38c3bf6d8241.png)
In this screenshot, both the `h1` and `.welcome-card-user` content are taking up two lines, and the `language-picker` block isn't even visible.

**Comment by everly-gif** [comment]
hey I would like to work on this issue. Please assign it to me

**Comment by everly-gif** [comment]
hey @rudokemper  I just reproduced this issue locally. Just to clarify , first of all this is a responsiveness issue right? Secondly , I'm not able to exactly reproduce the first screenshot . I see that the `.welcome-card-user` is forced to take up two lines in your screenshot whereas it only takes up one line in mine even when the `.language-picker` is pushed down out of the card(overflowing).  Although you claimed that the overflowing content isn't visible. I can actually see it as indicated in the screenshot. 

I also noticed  `.welcome-card-user` isn't translated to the language selected in mine unlike yours.
I find this strange, any suggestions what is going on here and we both have such different outputs?

Here's a screenshot
![welcome-terrastories](https://user-images.githubusercontent.com/77877486/137267221-383f3c11-085a-46cd-91f7-6352143c264f.png)

I do understand the base of the issue tho, the height doesn't adapt and we need to make it dynamic, in my opinion that can be done by changing one line of code in the `.welcome-card` stylesheet ,changing `height: 20rem to min-height:20rem`. I have tested it locally and the content doesn't overflow anymore and the height adapts. Is that something that would be fine?

Here's a screenshot after changing it:

![welcome-changes](https://user-images.githubusercontent.com/77877486/137268827-1187c82d-c789-4313-8953-9b95eb299393.png)

Just by comparing the above two screenshots you could tell the height has changed for the `.welcome-card`

**Comment by everly-gif** [comment]
https://docs.docker.com/compose/cli-command/ found this on docker's latest release notes. Apparently they are planning to deprecate the `docker-compose` command. I still don't the fix, help would be appreciated,

**Comment by everly-gif** [comment]
> @everly-gif I saw your messages about Docker not working after updating Windows, and the `service "extensions" has neither an image nor a build context specified: invalid compose project` you received. Did you end up resolving it? We're actually trying to figure out this issue on our Slack channel as well, you aren't the only one who's had this problem.

Yes I did, I was thinking of creating an issue separately on this , hence deleted the comments. 

To fix this : Go to settings>general> uncheck the box that says  "Use docker compose V2"(which is not set as default after updating to the latest version) apply and restart . 

Open powershell and type the commands. now docker-compose should work. I was able to successfully run it and make changes

Open powershell

**Comment by everly-gif** [comment]
I tried using `docker compose` commands instead of `docker-compose` and it gave me the same error `service "extensions" has neither an image nor a build context specified: invalid compose project`. Although acc to the documentation this small change should be more than sufficient, I am not sure why I get those errors. I'm not familiar with docker as much but I can try figuring this out
