### ISSUE TITLE
[Rails] Make "Community" and "Language" render as a typeahead field

### ISSUE THREAD

**Issue by rudokemper** [Terrastories/terrastories#687]
A number of the fields in Terrastories (such as `region`, `type_of_place`, and `topic`) are typeahead fields. 

There are two additional fields that should be made into typeahead fields as well: `community` (in the Speaker model) and `language` (in the Story model).

**Comment by ConnieJChi** [comment]
👋 Hello! Mind if I take this issue?

**Comment by rudokemper** [comment]
Hi @ConnieJChi! Thanks, and definitely :) Will assign you now.
