### ISSUE TITLE
[Server-side] Improve the messaging while the server is restarting

### ISSUE THREAD

**Issue by Bootjack** [Terrastories/terrastories#69]
Any time the rails and nginx server restarts, the application is unresponsive for up to a minute or so. During this time, there's a completely unhelpful generic 502 error from nginx. Let's improve that by adding a customized error page that looks more like the login page or something at least branded with the Terrastories logo.

Bonus points if we can also include client-side polling against an `/is_it_up` endpoint and automatically redirect to the app once the server is running.

**Comment by rudokemper** [comment]
Worked on by @robbkidd in these two PRs:

https://github.com/Terrastories/terrastories/pull/208
https://github.com/Terrastories/terrastories/pull/210

**Comment by mirandawang** [comment]
closing for now; moving details to issue google doc
