### ISSUE TITLE
Appealing Scroll Bar: Customized 

### ISSUE THREAD

**Issue by harshita214** [Terrastories/terrastories#706]
## Context:
To make scroll-bar more convenient and appealing for User, By making scroll-bar customized it makes look website's colours blend perfectly and make it look more professional. 

## How will it look
Below is example how I implement it

![scroll1](https://user-images.githubusercontent.com/79797000/143864994-d401217d-db86-4029-ab13-149ca280365c.PNG)

While scrolling

![scroll2](https://user-images.githubusercontent.com/79797000/143865195-cc6365b6-a509-4582-9e5f-616702227b6e.PNG)

**Comment by rudokemper** [comment]
Hi @harshita214 thanks for writing about this, and sorry for a delay in getting back to you. This repo is for submitting issues for the application, not the website, and before we opted not to customize the scrollbar for accessibility reasons. To keep things tidy on our Github I will close this issue, however, we will revisit this whenever we have the opportunity to rethink the website design.
