### ISSUE TITLE
[Server side] Guard against running bundler and rake tasks in local environment

### ISSUE THREAD

**Issue by Bootjack** [Terrastories/terrastories#74]
This project is set up to use Docker to help reduce the burden of configuring a new local development environment for every new contributor. It works great when it works, but an obvious flaw is that any developer can still run the app in their local environment, which may introduce the very environment-specific discrepancies that Docker is supposed to ward off, such as bundler version warnings.

I'm sure a talented open-source community member can figure out a way to prevent running rails directly in a local environment, or at least warn the developer about it. Either way, we should provide clear messaging with links to our documentation about the correct way to run rails-y stuff in this project.

**Comment by DarthHater** [comment]
This could likely be accomplished using `.dockerignore`, to prevent any bundler specific stuff (I can't remember where bundler stores stuff, but maybe it's in /vendor?) from making it into Docker via the `COPY . .`. Having worked on a similar Rails project (https://github.com/DCAFEngineering/dcaf_case_management), we ended up being pretty happy at the end of the day by just documenting how to run something locally, and via Docker, and suggesting Docker overall.

**Comment by mirandawang** [comment]
closing for now; moving details to issue google doc
