### ISSUE TITLE
[Map][React] Add full size / enlarged image mode for marker popups

### ISSUE THREAD

**Issue by rudokemper** [Terrastories/terrastories#796]
Currently, we display Place photos in a marker pop up as a regular IMG tag.

Let's add some functionality that allows us to view an enlarged version of the photo.

1) Add a button on the photo to signify enlargement
2) When clicking on that button, open an overlay or modal that displays a larger version of the photo.
3) Overlay / modal must be closed before interacting with the rest of the application.

Possible inspo: how Mapeo Web maps does this as can be seen here: http://wapichanao.communitylands.org/static-maps
(repo link: https://github.com/digidem/mapeo-webmaps-public)

**Comment by rudokemper** [comment]
In the same stroke, once we have this full size mode for marker popups built, we could truncate the text in popups at a reasonable quantity of characters.

![image](https://user-images.githubusercontent.com/31662219/193150098-9116ffe4-29ec-4357-8789-eba4c567dd77.png)

**Comment by Im-Kunal-13** [comment]
@rudokemper can you assign me this issue? I would like to work on it.

**Comment by rudokemper** [comment]
Hi @Im-Kunal-13, welcome! I assigned you :)
