### ISSUE TITLE
[Rails] Allow super admin to view a "last updated on ..." note next to communities on the main dashboard

### ISSUE THREAD

**Issue by rudokemper** [Terrastories/terrastories#803]
When logged in as a super admin (e.g. via username `super@terrastories.io` and password `terrastories` per the default seed data), we are able to view all of the communities on the dashboard accessed at the  `/en/member/communities` path. Let's add a `Last updated on $date` note on a new line following the name of the community, in italics.

This would track the last time that a change was made to the community database (e.g. adding or editing a Story, Speaker, Place, User, or a change made to the Theme).

It would look like this:
![image](https://user-images.githubusercontent.com/31662219/193126712-d98c4647-a09c-46f3-87d8-591418cb6dc6.png)

In so doing, let's add the "Last updated on" string to the i18n files so they can be translated.

**Comment by ashwini-seshadri** [comment]
Hi! I would like to work on this issue!
I have also signed up for hacktoberfest!

**Comment by rudokemper** [comment]
That's great @ashwini-seshadri! Thanks! I assigned you.

**Comment by rudokemper** [comment]
Hi @ashwini-seshadri just checking if you still wanted to work on this?

**Comment by rudokemper** [comment]
Awesome, sounds good @ashwini-seshadri :)
