### ISSUE TITLE
[CMS] Let's implement a responsive design for the new Terrastories CMS

### ISSUE THREAD

**Issue by rudokemper** [Terrastories/terrastories#804]
The newly merged Admin CMS refactor adds a whole new CMS to Terrastories, accessed at `/en/member/` when logged in to a community.

The layout of the CMS is not yet responsive. Let's put in some work to make this layout display better on different viewports.

_Current design loaded on a Samsung Galaxy phone_:

![image](https://user-images.githubusercontent.com/31662219/193127819-00ccb448-74df-406c-ac87-ed2ee09d0b0d.png)

**Comment by asheerrizvi** [comment]
@rudokemper I can take this. Do we have any design which we want to implement on smaller viewports?

**Comment by rudokemper** [comment]
Hi @asheerrizvi we do not; so I think a first step for this ticket would be to create some UI design mock-ups.

**Comment by asheerrizvi** [comment]
Cool, can you assign this to me? I'll have a look over the weekend @rudokemper

**Comment by rudokemper** [comment]
@asheerrizvi might you also want to work on a slight issue introduced by the latest PR focused on adapting the StoryList height? I just noticed this - when the sidebar is minimized, it is now impossible to zoom in on the map for about half of the left side of the screen.

**Comment by rudokemper** [comment]
Hi @asheerrizvi sorry I never responded to you. I'm not sure if it's still an issue. But were you still interested in working on this Issue? Let me know and I'll reassign you.
