### ISSUE TITLE
[Rails] Implement file size compression for media attachments

### ISSUE THREAD

**Issue by rudokemper** [Terrastories/terrastories#806]
Currently, media attachments (images, audio, video) that are uploaded to Terrastories are stored in the original filesize. Yet, these assets are only rendered on the front end in a relatively small size; the videos can be maximized to full screen, but are generally only viewed via standard computer monitors or smartphone devices. Ideally, these should be optimized for the web - in the current storage setup, they are taking up unnecessary storage space, and increase the load of bandwidth streaming, potentially causing performance issues.

**Comment by rudokemper** [comment]
There could be some resources to look into here: https://www.railsjazz.com/

**Comment by ashwini-seshadri** [comment]
Hi, I would like to work on this issue as well!

**Comment by rudokemper** [comment]
Hi @ashwini-seshadri! I assigned you :)

**Comment by ashwini-seshadri** [comment]
Hi, just an FYI, I have started to work on this issue!

**Comment by rudokemper** [comment]
@ashwini-seshadri hello! Just checking in to see if you were still interested. Let me know and I will reassign you.

**Comment by ashwini-seshadri** [comment]
@rudokemper Hello! I apologise, was a bit caught up. I am still interested in working on this issue and would like to submit a PR soon. Thank you!

**Comment by rudokemper** [comment]
Awesome! Thanks @ashwini-seshadri :)
