### ISSUE TITLE
[Rails] Fix a small line-height issue with text in the Speaker cards in the new CMS

### ISSUE THREAD

**Issue by rudokemper** [Terrastories/terrastories#807]
The new [Admin refactor branch](https://github.com/Terrastories/terrastories/tree/administrate-refactor-part-1) adds a whole new CMS to Terrastories, accessed at `/en/member/` when logged in to a community.

There is a minor issue with line-height in the Speaker cards in the new CMS:

![image](https://user-images.githubusercontent.com/31662219/193132088-afec790f-bbbb-4755-b260-88dca53b4d70.png)

**Comment by asheerrizvi** [comment]
I can take this @rudokemper

**Comment by rudokemper** [comment]
I think we actually ended up solving this recently; my bad for having this up still.
