### ISSUE TITLE
[Rails] add the ability for an admin user to upload their own map Home icon to Themes

### ISSUE THREAD

**Issue by rudokemper** [Terrastories/terrastories#811]
Long ago, we customized the standard Mapbox map controls home icon to be a house of the Matawai community:
![image](https://user-images.githubusercontent.com/31662219/193146179-f0f260d3-b682-4de7-88fe-06ae4466a2aa.png)

The intent was always to allow for communities to modify this icon to make it their own, but we haven't gotten around to it until now.

Let's make it possible by allowing an admin user to upload an SVG icon via the CMS themes page. Then, let's modify the `createHomeButton()` function in `Map.jsx` to set `.home-icon` `background-image` to the community's own SVG icon, or fallback to the one in our assets.

This may require some testing of different SVGs to ensure that it will work; there could be some idiosyncrasies to the SVG file structure that prevent it from rendering, in which case we could possibly add some validations.

For this work, use the new Terrastories CMS, accessed at `/en/member/` when logged in to a community.

**Comment by matisnape** [comment]
Hey, can I take this one? :)

**Comment by matisnape** [comment]
Question, should I already see the generic home icon here? 
<img width="352" alt="2022-10-16 22-08-13" src="https://user-images.githubusercontent.com/2719923/196055871-65d6b4c7-ea14-40bd-ac82-215a7512d7dc.png">
Do I really need the Mapbox account to complete this task? They require credit card which I don’t have

**Comment by rudokemper** [comment]
We followed up about the Mapbox account on Slack - but, I would note that you should see the Home icon if you go the ``--profile offline` route, without credit card. You just have to make sure to be entirely offline otherwise Mapbox GL JS will complain.

It does not relate to any data model e.g. places. It's simply an SVG icon that is being pulled from assets. The desired feature is the ability to add your own SVG icon in the Themes dashboard.
