### ISSUE TITLE
[Rails] Remove profile link from super admin dashboard

### ISSUE THREAD

**Issue by rudokemper** [Terrastories/terrastories#812]
When logged in as a super admin (e.g. via username `super@terrastories.io` and password `terrastories` per the default seed data), you access a unique dashboard for the super admin user. 

At the top right, there is a leftover `Profile` link from other user role dashboards, which is currently leading to an error page. Let's remove this link.

![image](https://user-images.githubusercontent.com/31662219/193417724-f9e87009-e9a4-4a63-a3cc-8fa1e20ff23b.png)

**Comment by asheerrizvi** [comment]
I can take this @rudokemper

**Comment by rudokemper** [comment]
Thanks @asheerrizvi! I assigned you.

**Comment by asheerrizvi** [comment]
@rudokemper should I branch out of `administrate-refactor-part-1` for this too?

**Comment by asheerrizvi** [comment]
@rudokemper have opened a PR for this: https://github.com/Terrastories/terrastories/pull/814

**Comment by rudokemper** [comment]
Hey @asheerrizvi we just merged that administrate refactor branch; can you submit your PRs for the main TS branch?

**Comment by asheerrizvi** [comment]
@rudokemper done, you can check now

**Comment by asheerrizvi** [comment]
@rudokemper we can close this as per Laura's comment on the PR:

https://github.com/Terrastories/terrastories/pull/814#issuecomment-1265545904

**Comment by rudokemper** [comment]
Thanks @asheerrizvi; sorry for the miscommunication on this one.
