### ISSUE TITLE
[Rails][React] Add the ability to "pin" a story so it shows up first on the StoryList

### ISSUE THREAD

**Issue by rudokemper** [Terrastories/terrastories#825]
The Haudenosaunee community has requested that we add a feature to "pin" a story, so that it shows up first on the StoryList. Let's make it happen!

Let's go about this the following way (working with the new CMS in the `/member/` path):

1. In the CMS, for a user with `editor` or `admin` permissions, add the ability to "pin" a story by showing an `icon-pushpin` from font-awesome in the top right of a Story card upon hover over the card.
![image](https://user-images.githubusercontent.com/31662219/193712987-069298dd-3390-439e-b8a7-f94e946ae9f8.png)
2. Upon hovering over the `icon-pushpin`, the icon should be highlighted with a box-shadow in the same way that the card is highlighted upon hover.
3. Users with `member` permissions are able to see that a story is pinned, but can't themselves pin or unpin any stories. (And they do not see any hover box-shadow behavior.)
4. Once clicked, the Story card should move to the top of the list (top left in the CMS).
5. Additionally, on the application front end (`/home/`), the story should show first in the StoryList in the sidebar, regardless of how the story is sorted, and the `icon-pushpin` should show up in the top right here, too.
![image](https://user-images.githubusercontent.com/31662219/193713254-d9eface2-6e8b-47d1-9947-b440d2da5e9f.png)
6. However, if either on the CMS side or the application front end, the stories are filtered in such a way that the pinned story does not meet the criteria, it should disappear from the list.
7. In the CMS, once a story has been pinned, a user with `editor` or `admin` permissions can unpin the story by clicking on the `icon-pushpin` in the top right, which removes it from being pinned and returns it to its normal order in the list of stories.
8. Default state is that no stories are pinned. 

Bonus if the user can somehow see the "pinned" story move to the top of the list in the CMS (e.g. by briefly fading out from current position, and fading in to top level) -- and vice versa if unpinned -- but not necessary for completion.

**Comment by shub78910** [comment]
I'd like to work on this, can you please assign this to me?
Also, If I try to create a Mapbox account, it asks me for my credit card details. Is there a dummy key, which I can use for development? That'd be great, thanks.

**Comment by rudokemper** [comment]
Hi @shub78910 sure. Can you message me on our Slack channel, or on Discord (rkemper#8724)? I'll share it with you there.

**Comment by shub78910** [comment]
Sure
