### ISSUE TITLE
[Translation] Help us add more translations to Terrastories! (and update Spanish/Portuguese/Dutch/Japanese)

### ISSUE THREAD

**Issue by rudokemper** [Terrastories/terrastories#826]
We've been slacking on keeping our Spanish, Portuguese, Dutch, and Japanese translations in `/rails/config/locales` up to date as we've been adding more strings to the app. Also, we would love to add more languages to Terrastories! If you would either like to help us keep our translations complete, or add a new language, that would be amazing!

Process for adding a new language:
1. Find the two or three-digit ISO language code for your language contribution [here](https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes)
2. Copy the `en` folder and rename it to your ISO language code. Also rename the `en` in each filename, and the beginning of each file, to your ISO language code.
3. Translate each string to your language of contribution.
4. Add your language to the `languages` list for all of the languages (in `en.yml`, `pt.yml`, `mat.yml`, ... and your new language contribution). You can use Google Translate to figure out how your language is translated in the other languages.
5. Submit your PR 🎉 

Please note that we can't merge PRs until at least the core content of `en.yml` has been translated, since that is what feeds the front end of the app. It is recommended to submit a PR with all of the translations at once, but if you want to do them piece-meal instead, please start with `en.yml`.

Updates:
- [X] Spanish
- [X] Dutch
- [X] Matawai
- [X] Chinese
- [x] Portuguese
- [ ] Japanese

**Comment by larymak** [comment]
Can I add a Swahili translation to the same?

**Comment by rudokemper** [comment]
@larymak absolutely! We would love to have Swahili!

**Comment by KrunkZhou** [comment]
Can I add a Chinese translation?

**Comment by rudokemper** [comment]
@KrunkZhou that would be wonderful! :)

**Comment by julinvictus** [comment]
I'm doing the PT one

**Comment by julinvictus** [comment]
Wanted to check with you @rudokemper what you think about trying to use gender-neutral expressions. Latin languages like Portuguese will always genderize everything, but there's a tendency now to try to use those gender-neutral expressions, for instance, Welcome screen could be 'Bem vinde', now is 'Bem vindo/a'.

**Comment by rudokemper** [comment]
Great question @julinvictus. I thought about this, and went back and forth on it a little. On the one hand, some of our users are not likely to know gender-neutral expressions, but on the other hand, we want to be inclusive and I checked with some peer applications and platforms that are already using these as well. So I'd say let's go with the gender neutral expressions 👍 thanks for asking!

**Comment by arefathi** [comment]
Hello there, this is really a cool project. 
I would like to make Amharic translation contributions. 
Please let me know if that's okay before I proceed. Thanks.

**Comment by rudokemper** [comment]
@arefathi that would be amazing!! Thank you!

**Comment by arefathi** [comment]
> @arefathi that would be amazing!! Thank you!

Hello again @rudokemper
I have submitted a PR for the Amharic `am` translation at PR #857 
Thanks for the opportunity. It was fun working on this.

**Comment by anattolia** [comment]
Hi! Is the Spanish translation complete now?

**Comment by rudokemper** [comment]
Hi @anattolia yes, but please do feel free to screen the translations to ensure they are okay. I think some of it was Google Translate 😅

**Comment by AshishSharma1203** [comment]
@rudokemper I have added Hindi language translation ( only hi.yml as for now ). I will add the remaining file translations step by step. 
Please verify this one and merge it.

**Comment by ambrolla** [comment]
I can add Russian translation too.

**Comment by rudokemper** [comment]
That would be great @ambrolla !

**Comment by mithindev** [comment]
"Hi @rudokemper, I've made an addition of a Korean language translation. Would you be able to take a look and verify it for me?

**Comment by Fennec92** [comment]
Hey, do you need German?

**Comment by rudokemper** [comment]
@mithindev thanks! I will when I get the chance (or anyone else from stewards team is welcome to as well in the meantime).

@Fennec92 sure, any languages are welcome

**Comment by nilling4** [comment]
Hi, I was wondering if I could add a Japanese translation?

**Comment by mithindev** [comment]
Can I work on this, please.

**Comment by rudokemper** [comment]
Hi folks, assigned you for now - I'll try to see if I can do a review in the next two weeks.
