### ISSUE TITLE
[Rails] Let's add a hover tooltip over language choices in the new CMS

### ISSUE THREAD

**Issue by rudokemper** [Terrastories/terrastories#844]
The new CMS (located at `/member/`) adds the ability to pick a language from within the CMS. Right now, these are showing as acronyms in the bottom left (e.g. EN, ES, PT...). A user might not know what these acronyms stand for.

1. Let's add the full language strings for each language (English, Spanish, Portuguese...)  to each language's dashboard yml file. Bonus if you actually translate the languages into each existing language (English, Español, Espanhol...); Google translate should cover that just fine!
2. Let's add a hover tooltip displaying the localized language string per each language, akin to how we have hover tooltips for Speakers in Stories (see screenshot below).

![image](https://user-images.githubusercontent.com/31662219/194567191-796018e0-7433-4480-b1c3-8a065630e0f9.png)

**Comment by nikhilbhatt** [comment]
@rudokemper can I take this?

**Comment by rudokemper** [comment]
@nikhilbhatt sure! I assigned you, thanks!
