### ISSUE TITLE
[Map] Fix sprite rendering in the style json for tileserver

### ISSUE THREAD

**Issue by rudokemper** [Terrastories/terrastories#85]
Currently, sprites are not working on the map and the following errors appear on dev tools console:

![image](https://user-images.githubusercontent.com/31662219/55911212-241f9f00-5bae-11e9-9cc0-f7b66a170b1b.png)

We also need a workflow for adding custom SVG's for graphic icons. This map (https://amazonteam.org/maps/matawai-oral-histories/map.html) has some icons for point features:

![image](https://user-images.githubusercontent.com/31662219/55911367-7c56a100-5bae-11e9-8d9f-e657e39cbb29.png)

How can we get these to render in Terrastories?

**Comment by rudokemper** [comment]
Maybe worth looking at this code? https://github.com/digidem/mapbox-style-downloader

**Comment by mirandawang** [comment]
closing for now; moving details to issue google doc
