### ISSUE TITLE
[Rails] Set validation for media blob attachments for Story model

### ISSUE THREAD

**Issue by rudokemper** [Terrastories/terrastories#853]
Currently the media blob attachment for the Story model lacks validation. Let's add audio, video, and image.

**Comment by navaneethkp36** [comment]
hi @rudokemper I would like to contribute to this

**Comment by rudokemper** [comment]
Hi @navaneethkp36 I got started on this https://github.com/Terrastories/terrastories/pull/854 but I think we could still do some more work to make this more nuanced; with this validation we can still upload 3gp which doesn't render well in html5. Want to take a look?
