### ISSUE TITLE
[Bug] When a new language is added to Terrastories, values don't show on the front end until another change is made to i18n

### ISSUE THREAD

**Issue by rudokemper** [Terrastories/terrastories#856]
Terrastories is using Ruby i18n to provide languages. These are added to `rails/config/locales`.

There is a short bit of code in `rails/config/application.rb` that automatically sets the available locales to whatever is found in that directory. 

However, when you first add a new language to Terrastories, it seems to not load the values (from `en.yml` or equivalent) on the front end at first, as per the screenshot below. It _does_ load everywhere else in the application (e.g. devise, administrate, dashboard, model, as well as the welcome page which also loads values from `en.yml` or equivalent).

Then, once you make a change to _any_ of the locales, it _will_ load the front end translations for that new language.

Let's solve this problem so that the front end loads the new locale values right away.

Steps to reproduce:
1. Make sure that you've started Terrastories at least once.
1. Copy the `en` folder in `locales` and name it any other language acronym; this can be arbitrary, but you could use, say, Italian with `it`.
2. Replace `en` to `it` in all of the filenames, as well as in the first line of each file.
3. Start Terrastories. You should see the "missing translation" messages on the front end (`/home/`) despite being set properly in the `it.yml` file.

![Missing translations bug](https://user-images.githubusercontent.com/31662219/195993003-b7e54c35-5719-4a3a-8786-e19e8f760727.jpg)

**Comment by rudokemper** [comment]
You can see this with the recently merged Aramaic translations in the master branch.

![image](https://user-images.githubusercontent.com/31662219/196582200-e0763c53-142b-4cf7-9465-30000ba0d0e8.png)

**Comment by DuldR** [comment]
If this is still available, i'd like to take a crack it!

**Comment by rudokemper** [comment]
Thanks @DuldR ! I assigned you.

**Comment by DuldR** [comment]
@rudokemper 

> Then, once you make a change to _any_ of the locales, it _will_ load the front end translations for that new language.

I can't seem to get this portion to reproduce. What changes can I make to the other locales so that it will load correctly? Do you mean in the `yml` files?

**Comment by rudokemper** [comment]
@DuldR yes in the `yml` files. Update any of the translations in the existing yml files. It should "fix" the problem of the missing ones.
