### ISSUE TITLE
[Open source] add PR `template.md` file

### ISSUE THREAD

**Issue by AshishSharma1203** [Terrastories/terrastories#863]
Thanks for adding an issue to Terrastories! Reach out to us in Slack or at terrastories-stewards@googlegroups.com if you have any questions about creating an issue.

## Context:
Include why this issue is needed & any relevant context.

to add PR_template.md file 

## Acceptance criteria:

- [ ] Acceptance criteria goes here, e.g. “User is able to filter by region”
- [ ] Existing tests do not break
- [ ] Add unit tests for any new functionality
- [ ] \(Optional) Create an integration test for any new feature

## Assets
Please link or attach any required assets, mocks, or copy

**Comment by ambrolla** [comment]
Hello!
I was curious if someone is working on this and if not, I didn't fully understand what is the issue that needs to be resolved?

Thanks.

**Comment by AshishSharma1203** [comment]
I did raised this issue to make the pull request more organised and clear by including a PR template.md file. 
I wasn't assigned this issue so I didn't made any changes to the code. Hence the issue is still left unassigned .

**Comment by rudokemper** [comment]
Sorry if this is unclear from our side, but the way we assign is for someone to volunteer and then we do it. So it would be fine for either of you to take this on :) thanks!

**Comment by AshishSharma1203** [comment]
> Sorry if this is unclear from our side, but the way we assign is for someone to volunteer and then we do it. So it would be fine for either of you to take this on :) thanks!

okay!!! I will wish to work on this particular issue.

**Comment by AshishSharma1203** [comment]
@rudokemper  I have made the pull request. Please verify it and if any further improvements are required then please notify soo.
