### ISSUE TITLE
Docker build error

### ISSUE THREAD

**Issue by NyakudyaA** [Terrastories/terrastories#897]
Thanks for adding a bug to Terrastories! Reach out to us in Slack or at terrastories-stewards@googlegroups.com if you have any questions about creating a bug.

**Describe the bug**

**To Reproduce**
1. Clone the repository
2. execute `./bin/setup`
3. See error below

```
#0 57.02 ERROR:  Error installing rubygems-update:
#0 57.02 	There are no versions of rubygems-update (= 3.4.3) compatible with your Ruby & RubyGems
#0 57.02 	rubygems-update requires Ruby version >= 2.6.0. The current ruby version is 2.5.9.229.
#0 57.02 ERROR:  While executing gem ... (Errno::ENOENT)
#0 57.02     No such file or directory @ dir_chdir - /usr/local/bundle/gems/rubygems-update-3.0.3
```

**Expected behavior**
A successful build

# OS
ubuntu 22.04

**Comment by albertchae** [comment]
Hey @NyakudyaA, I ran into this issue too and put up a PR to address it https://github.com/Terrastories/terrastories/pull/900
