### ISSUE TITLE
[Rails][Bug] Birthplace field for Speakers is not updating via the Speaker edit form

### ISSUE THREAD

**Issue by rudokemper** [Terrastories/terrastories#953]
**Describe the bug**
For Speakers, it is possible to assign a Birthplace. This works upon initial creation.

However, when trying to update the Birthplace via the dashboard Speaker edit view from location A to location B, the form will successfully be saved, however the speaker will continue to have location A.

**To Reproduce**
1. As a logged in Terrastories community admin, create a new Speaker and assign it a birthplace.
2. Then, edit the Speaker, and assign it a different birthplace.
3. See that the birthplace will continue to be the original value.

**Expected behavior**
In the above example, the speaker birthday is set to location B.

**Comment by Br0k3nh4nd012** [comment]
@rudokemper Can I work on this?

**Comment by rudokemper** [comment]
Sure! I assigned you.
